/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`create_sepa_direct_debit_api`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateSepaDirectDebitApiError {
    Status500(),
    UnknownValue(serde_json::Value),
}


pub async fn create_sepa_direct_debit_api(configuration: &configuration::Configuration, creditor_name: &str, creditor_iban: &str, creditor_id: &str, mandate_id: &str, mandate_date: &str, debtor_name: &str, debtor_iban: &str, amount: &str, collection_date: &str, creditor_bic: Option<&str>, debtor_bic: Option<&str>, description: Option<&str>) -> Result<models::SepaDirectDebitResponse, Error<CreateSepaDirectDebitApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_creditor_name = creditor_name;
    let p_query_creditor_iban = creditor_iban;
    let p_query_creditor_id = creditor_id;
    let p_query_mandate_id = mandate_id;
    let p_query_mandate_date = mandate_date;
    let p_query_debtor_name = debtor_name;
    let p_query_debtor_iban = debtor_iban;
    let p_query_amount = amount;
    let p_query_collection_date = collection_date;
    let p_query_creditor_bic = creditor_bic;
    let p_query_debtor_bic = debtor_bic;
    let p_query_description = description;

    let uri_str = format!("{}/api/v1/bookkeeping/sepa-direct-debit", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.query(&[("creditor_name", &p_query_creditor_name.to_string())]);
    req_builder = req_builder.query(&[("creditor_iban", &p_query_creditor_iban.to_string())]);
    if let Some(ref param_value) = p_query_creditor_bic {
        req_builder = req_builder.query(&[("creditor_bic", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("creditor_id", &p_query_creditor_id.to_string())]);
    req_builder = req_builder.query(&[("mandate_id", &p_query_mandate_id.to_string())]);
    req_builder = req_builder.query(&[("mandate_date", &p_query_mandate_date.to_string())]);
    req_builder = req_builder.query(&[("debtor_name", &p_query_debtor_name.to_string())]);
    req_builder = req_builder.query(&[("debtor_iban", &p_query_debtor_iban.to_string())]);
    if let Some(ref param_value) = p_query_debtor_bic {
        req_builder = req_builder.query(&[("debtor_bic", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("amount", &p_query_amount.to_string())]);
    req_builder = req_builder.query(&[("collection_date", &p_query_collection_date.to_string())]);
    if let Some(ref param_value) = p_query_description {
        req_builder = req_builder.query(&[("description", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SepaDirectDebitResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::SepaDirectDebitResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateSepaDirectDebitApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

