/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`datev_export_api`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DatevExportApiError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`datev_preview_api`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DatevPreviewApiError {
    UnknownValue(serde_json::Value),
}


pub async fn datev_export_api(configuration: &configuration::Configuration, account_schema: Option<&str>, date_from: Option<&str>, date_to: Option<&str>, page: Option<i32>, page_size: Option<i32>) -> Result<models::DatevExportResponse, Error<DatevExportApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_account_schema = account_schema;
    let p_query_date_from = date_from;
    let p_query_date_to = date_to;
    let p_query_page = page;
    let p_query_page_size = page_size;

    let uri_str = format!("{}/api/v1/bookkeeping/datev/export", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_account_schema {
        req_builder = req_builder.query(&[("account_schema", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_date_from {
        req_builder = req_builder.query(&[("date_from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_date_to {
        req_builder = req_builder.query(&[("date_to", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_size {
        req_builder = req_builder.query(&[("page_size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DatevExportResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DatevExportResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DatevExportApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn datev_preview_api(configuration: &configuration::Configuration, account_schema: Option<&str>, date_from: Option<&str>, date_to: Option<&str>, page: Option<i32>, page_size: Option<i32>) -> Result<Vec<models::DatevBookingPreview>, Error<DatevPreviewApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_account_schema = account_schema;
    let p_query_date_from = date_from;
    let p_query_date_to = date_to;
    let p_query_page = page;
    let p_query_page_size = page_size;

    let uri_str = format!("{}/api/v1/bookkeeping/datev/preview", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_account_schema {
        req_builder = req_builder.query(&[("account_schema", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_date_from {
        req_builder = req_builder.query(&[("date_from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_date_to {
        req_builder = req_builder.query(&[("date_to", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_size {
        req_builder = req_builder.query(&[("page_size", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::DatevBookingPreview&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::DatevBookingPreview&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DatevPreviewApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

