/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`create_inventory_count`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateInventoryCountError {
    Status400(models::PluginError),
    Status500(models::PluginError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_inventory_count`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteInventoryCountError {
    Status400(models::PluginError),
    Status404(models::PluginError),
    Status500(models::PluginError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`generate_inventory_count`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GenerateInventoryCountError {
    Status400(models::PluginError),
    Status500(models::PluginError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_inventory_count`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetInventoryCountError {
    Status404(models::PluginError),
    Status500(models::PluginError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_inventory_counts`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListInventoryCountsError {
    Status500(models::PluginError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_inventory_count`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateInventoryCountError {
    Status400(models::PluginError),
    Status404(models::PluginError),
    Status500(models::PluginError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_inventory_count_status`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateInventoryCountStatusError {
    Status400(models::PluginError),
    Status404(models::PluginError),
    Status500(models::PluginError),
    UnknownValue(serde_json::Value),
}


pub async fn create_inventory_count(configuration: &configuration::Configuration, inventory_count: models::InventoryCount) -> Result<models::InventoryCount, Error<CreateInventoryCountError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_inventory_count = inventory_count;

    let uri_str = format!("{}/api/v1/inventory-counts", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_inventory_count);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InventoryCount`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InventoryCount`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateInventoryCountError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn delete_inventory_count(configuration: &configuration::Configuration, inventory_count_id: &str) -> Result<(), Error<DeleteInventoryCountError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_inventory_count_id = inventory_count_id;

    let uri_str = format!("{}/api/v1/inventory-counts/{inventory_count_id}", configuration.base_path, inventory_count_id=crate::apis::urlencode(p_path_inventory_count_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteInventoryCountError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn generate_inventory_count(configuration: &configuration::Configuration, generate_count_request: models::GenerateCountRequest) -> Result<models::InventoryCount, Error<GenerateInventoryCountError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_generate_count_request = generate_count_request;

    let uri_str = format!("{}/api/v1/inventory-counts/generate", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_generate_count_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InventoryCount`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InventoryCount`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GenerateInventoryCountError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_inventory_count(configuration: &configuration::Configuration, inventory_count_id: &str) -> Result<models::InventoryCount, Error<GetInventoryCountError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_inventory_count_id = inventory_count_id;

    let uri_str = format!("{}/api/v1/inventory-counts/{inventory_count_id}", configuration.base_path, inventory_count_id=crate::apis::urlencode(p_path_inventory_count_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InventoryCount`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InventoryCount`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetInventoryCountError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn list_inventory_counts(configuration: &configuration::Configuration, page: Option<i32>, page_size: Option<i32>, status: Option<&str>, warehouse_id: Option<&str>) -> Result<Vec<models::InventoryCount>, Error<ListInventoryCountsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_page = page;
    let p_query_page_size = page_size;
    let p_query_status = status;
    let p_query_warehouse_id = warehouse_id;

    let uri_str = format!("{}/api/v1/inventory-counts/", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_size {
        req_builder = req_builder.query(&[("page_size", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_status {
        req_builder = req_builder.query(&[("status", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_warehouse_id {
        req_builder = req_builder.query(&[("warehouse_id", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::InventoryCount&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::InventoryCount&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListInventoryCountsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn update_inventory_count(configuration: &configuration::Configuration, inventory_count_id: &str, body: Option<serde_json::Value>) -> Result<models::InventoryCount, Error<UpdateInventoryCountError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_inventory_count_id = inventory_count_id;
    let p_body_body = body;

    let uri_str = format!("{}/api/v1/inventory-counts/{inventory_count_id}", configuration.base_path, inventory_count_id=crate::apis::urlencode(p_path_inventory_count_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InventoryCount`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InventoryCount`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateInventoryCountError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn update_inventory_count_status(configuration: &configuration::Configuration, inventory_count_id: &str, inventory_count_status_update: models::InventoryCountStatusUpdate) -> Result<models::InventoryCount, Error<UpdateInventoryCountStatusError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_inventory_count_id = inventory_count_id;
    let p_body_inventory_count_status_update = inventory_count_status_update;

    let uri_str = format!("{}/api/v1/inventory-counts/{inventory_count_id}/status", configuration.base_path, inventory_count_id=crate::apis::urlencode(p_path_inventory_count_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_inventory_count_status_update);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InventoryCount`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InventoryCount`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateInventoryCountStatusError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

