/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`list_open_items_api`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListOpenItemsApiError {
    Status500(),
    UnknownValue(serde_json::Value),
}


pub async fn list_open_items_api(configuration: &configuration::Configuration, reminder_level1_days: Option<i64>, reminder_level2_days: Option<i64>, reminder_level3_days: Option<i64>, customer_id: Option<&str>) -> Result<Vec<models::OpenItem>, Error<ListOpenItemsApiError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_reminder_level1_days = reminder_level1_days;
    let p_query_reminder_level2_days = reminder_level2_days;
    let p_query_reminder_level3_days = reminder_level3_days;
    let p_query_customer_id = customer_id;

    let uri_str = format!("{}/api/v1/bookkeeping/open-items", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_reminder_level1_days {
        req_builder = req_builder.query(&[("reminder_level1_days", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_reminder_level2_days {
        req_builder = req_builder.query(&[("reminder_level2_days", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_reminder_level3_days {
        req_builder = req_builder.query(&[("reminder_level3_days", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_customer_id {
        req_builder = req_builder.query(&[("customer_id", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::OpenItem&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::OpenItem&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListOpenItemsApiError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

