/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`create_warehouse_stock`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateWarehouseStockError {
    Status400(models::PluginError),
    Status500(models::PluginError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_warehouse_stock`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteWarehouseStockError {
    Status404(models::PluginError),
    Status500(models::PluginError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_warehouse_stock`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListWarehouseStockError {
    Status500(models::PluginError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_warehouse_stock`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateWarehouseStockError {
    Status404(models::PluginError),
    Status500(models::PluginError),
    UnknownValue(serde_json::Value),
}


pub async fn create_warehouse_stock(configuration: &configuration::Configuration, warehouse_id: &str, stock_adjustment: models::StockAdjustment) -> Result<models::WarehouseStock, Error<CreateWarehouseStockError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_warehouse_id = warehouse_id;
    let p_body_stock_adjustment = stock_adjustment;

    let uri_str = format!("{}/api/v1/warehouses/{warehouse_id}/stock", configuration.base_path, warehouse_id=crate::apis::urlencode(p_path_warehouse_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_stock_adjustment);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WarehouseStock`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WarehouseStock`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateWarehouseStockError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn delete_warehouse_stock(configuration: &configuration::Configuration, warehouse_id: &str, product_id: &str) -> Result<(), Error<DeleteWarehouseStockError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_warehouse_id = warehouse_id;
    let p_path_product_id = product_id;

    let uri_str = format!("{}/api/v1/warehouses/{warehouse_id}/stock/{product_id}", configuration.base_path, warehouse_id=crate::apis::urlencode(p_path_warehouse_id), product_id=crate::apis::urlencode(p_path_product_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteWarehouseStockError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn list_warehouse_stock(configuration: &configuration::Configuration, warehouse_id: &str) -> Result<Vec<models::WarehouseStock>, Error<ListWarehouseStockError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_warehouse_id = warehouse_id;

    let uri_str = format!("{}/api/v1/warehouses/{warehouse_id}/stock", configuration.base_path, warehouse_id=crate::apis::urlencode(p_path_warehouse_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::WarehouseStock&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::WarehouseStock&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListWarehouseStockError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn update_warehouse_stock(configuration: &configuration::Configuration, warehouse_id: &str, product_id: &str, stock_adjustment: models::StockAdjustment) -> Result<models::WarehouseStock, Error<UpdateWarehouseStockError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_warehouse_id = warehouse_id;
    let p_path_product_id = product_id;
    let p_body_stock_adjustment = stock_adjustment;

    let uri_str = format!("{}/api/v1/warehouses/{warehouse_id}/stock/{product_id}", configuration.base_path, warehouse_id=crate::apis::urlencode(p_path_warehouse_id), product_id=crate::apis::urlencode(p_path_product_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_stock_adjustment);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WarehouseStock`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WarehouseStock`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateWarehouseStockError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

