/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Absence {
    /// One of \"vacation\", \"sick\", \"sabbatical\", \"parental\", \"other\".
    #[serde(rename = "absenceType", skip_serializing_if = "Option::is_none")]
    pub absence_type: Option<models::AbsenceType>,
    #[serde(rename = "approvedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub approved_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// References the user entity.
    #[serde(rename = "approvedBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub approved_by: Option<Option<uuid::Uuid>>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "deletedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// References the employee entity.
    #[serde(rename = "employeeId", skip_serializing_if = "Option::is_none")]
    pub employee_id: Option<uuid::Uuid>,
    #[serde(rename = "endDate", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<chrono::NaiveDate>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "notes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Option<String>>,
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<chrono::NaiveDate>,
    /// One of \"pending\", \"approved\", \"rejected\", \"cancelled\".
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::AbsenceStatus>,
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<uuid::Uuid>,
    #[serde(rename = "updatedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
}

impl Absence {
    pub fn new() -> Absence {
        Absence {
            absence_type: None,
            approved_at: None,
            approved_by: None,
            created_at: None,
            deleted_at: None,
            employee_id: None,
            end_date: None,
            id: None,
            notes: None,
            start_date: None,
            status: None,
            tenant_id: None,
            updated_at: None,
        }
    }
}

