/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivityUpdate {
    /// One of: call | email | meeting | task | note
    #[serde(rename = "activityType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub activity_type: Option<Option<models::ActivityType>>,
    /// User responsible (`employee.employee_id`).
    #[serde(rename = "assignedTo", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub assigned_to: Option<Option<String>>,
    /// Contact this activity belongs to (`contact.contact_id`). References the contact entity.
    #[serde(rename = "contactId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub contact_id: Option<Option<String>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// Follow-up / Wiedervorlage date. Open activities with a due date in the past are overdue.
    #[serde(rename = "dueDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub due_date: Option<Option<chrono::NaiveDate>>,
    /// When to remind about the follow-up.
    #[serde(rename = "reminderDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reminder_date: Option<Option<chrono::NaiveDate>>,
    /// One of: open | done | cancelled
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<models::ActivityStatus>>,
    /// Short subject line.
    #[serde(rename = "subject", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subject: Option<Option<String>>,
}

impl ActivityUpdate {
    pub fn new() -> ActivityUpdate {
        ActivityUpdate {
            activity_type: None,
            assigned_to: None,
            contact_id: None,
            description: None,
            due_date: None,
            reminder_date: None,
            status: None,
            subject: None,
        }
    }
}

