/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiWorkerConfig {
    #[serde(rename = "auto_reply")]
    pub auto_reply: bool,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "max_tool_calls")]
    pub max_tool_calls: i32,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "system_prompt")]
    pub system_prompt: String,
    #[serde(rename = "tenant_id")]
    pub tenant_id: uuid::Uuid,
    #[serde(rename = "trigger_on")]
    pub trigger_on: Vec<String>,
    #[serde(rename = "updated_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
}

impl AiWorkerConfig {
    pub fn new(auto_reply: bool, created_at: chrono::DateTime<chrono::FixedOffset>, id: uuid::Uuid, is_active: bool, max_tool_calls: i32, model: String, name: String, provider: String, system_prompt: String, tenant_id: uuid::Uuid, trigger_on: Vec<String>) -> AiWorkerConfig {
        AiWorkerConfig {
            auto_reply,
            created_at,
            id,
            is_active,
            max_tool_calls,
            model,
            name,
            provider,
            system_prompt,
            tenant_id,
            trigger_on,
            updated_at: None,
        }
    }
}

