/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttachmentCreate {
    /// Contact this attachment belongs to (per-contact DMS). References the contact entity.
    #[serde(rename = "contactId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub contact_id: Option<Option<String>>,
    #[serde(rename = "fileName")]
    pub file_name: String,
    #[serde(rename = "fileSize", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub file_size: Option<Option<i64>>,
    #[serde(rename = "mimeType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<Option<String>>,
    #[serde(rename = "originalName")]
    pub original_name: String,
    #[serde(rename = "pdfaPath", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pdfa_path: Option<Option<String>>,
    #[serde(rename = "sha256Hash", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sha256_hash: Option<Option<String>>,
    #[serde(rename = "uploadedBy", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub uploaded_by: Option<Option<uuid::Uuid>>,
}

impl AttachmentCreate {
    pub fn new(file_name: String, original_name: String) -> AttachmentCreate {
        AttachmentCreate {
            contact_id: None,
            file_name,
            file_size: None,
            mime_type: None,
            original_name,
            pdfa_path: None,
            sha256_hash: None,
            uploaded_by: None,
        }
    }
}

