/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BoxFit {
    #[serde(rename = "height_cm")]
    pub height_cm: f64,
    #[serde(rename = "item_count")]
    pub item_count: i32,
    #[serde(rename = "length_cm")]
    pub length_cm: f64,
    #[serde(rename = "volume_cm3")]
    pub volume_cm3: f64,
    #[serde(rename = "width_cm")]
    pub width_cm: f64,
}

impl BoxFit {
    pub fn new(height_cm: f64, item_count: i32, length_cm: f64, volume_cm3: f64, width_cm: f64) -> BoxFit {
        BoxFit {
            height_cm,
            item_count,
            length_cm,
            volume_cm3,
            width_cm,
        }
    }
}

