/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BwaSummary {
    #[serde(rename = "gross_profit")]
    pub gross_profit: String,
    #[serde(rename = "net_profit")]
    pub net_profit: String,
    #[serde(rename = "open_invoices_count")]
    pub open_invoices_count: i64,
    #[serde(rename = "open_invoices_total")]
    pub open_invoices_total: String,
    #[serde(rename = "overdue_invoices_count")]
    pub overdue_invoices_count: i64,
    #[serde(rename = "overdue_invoices_total")]
    pub overdue_invoices_total: String,
    #[serde(rename = "profit_margin")]
    pub profit_margin: f64,
}

impl BwaSummary {
    pub fn new(gross_profit: String, net_profit: String, open_invoices_count: i64, open_invoices_total: String, overdue_invoices_count: i64, overdue_invoices_total: String, profit_margin: f64) -> BwaSummary {
        BwaSummary {
            gross_profit,
            net_profit,
            open_invoices_count,
            open_invoices_total,
            overdue_invoices_count,
            overdue_invoices_total,
            profit_margin,
        }
    }
}

