/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BwaReport {
    #[serde(rename = "expenses")]
    pub expenses: Box<models::BwaExpenses>,
    #[serde(rename = "generated_at")]
    pub generated_at: String,
    #[serde(rename = "period")]
    pub period: String,
    #[serde(rename = "revenue")]
    pub revenue: Box<models::BwaRevenue>,
    #[serde(rename = "summary")]
    pub summary: Box<models::BwaSummary>,
}

impl BwaReport {
    pub fn new(expenses: models::BwaExpenses, generated_at: String, period: String, revenue: models::BwaRevenue, summary: models::BwaSummary) -> BwaReport {
        BwaReport {
            expenses: Box::new(expenses),
            generated_at,
            period,
            revenue: Box::new(revenue),
            summary: Box::new(summary),
        }
    }
}

