/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContactHistoryResponse : Aggregated history for a single contact: all communications plus a lightweight per-channel breakdown.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContactHistoryResponse {
    #[serde(rename = "contactId")]
    pub contact_id: String,
    #[serde(rename = "inboundCount")]
    pub inbound_count: i64,
    #[serde(rename = "items")]
    pub items: Vec<models::CustomerCommunication>,
    #[serde(rename = "outboundCount")]
    pub outbound_count: i64,
}

impl ContactHistoryResponse {
    /// Aggregated history for a single contact: all communications plus a lightweight per-channel breakdown.
    pub fn new(contact_id: String, inbound_count: i64, items: Vec<models::CustomerCommunication>, outbound_count: i64) -> ContactHistoryResponse {
        ContactHistoryResponse {
            contact_id,
            inbound_count,
            items,
            outbound_count,
        }
    }
}

