/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CouponCreate {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "discountType")]
    pub discount_type: models::DiscountType,
    #[serde(rename = "discountValue")]
    pub discount_value: String,
    #[serde(rename = "expiresAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "isActive", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(rename = "isCombineable", skip_serializing_if = "Option::is_none")]
    pub is_combineable: Option<bool>,
    #[serde(rename = "maxDiscountAmount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_discount_amount: Option<Option<String>>,
    #[serde(rename = "maxUses", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_uses: Option<Option<i32>>,
    #[serde(rename = "maxUsesPerCustomer", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_uses_per_customer: Option<Option<i32>>,
    #[serde(rename = "minOrderAmount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub min_order_amount: Option<Option<String>>,
    #[serde(rename = "productIds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub product_ids: Option<Option<serde_json::Value>>,
    #[serde(rename = "startsAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub starts_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
}

impl CouponCreate {
    pub fn new(code: String, discount_type: models::DiscountType, discount_value: String) -> CouponCreate {
        CouponCreate {
            code,
            description: None,
            discount_type,
            discount_value,
            expires_at: None,
            is_active: None,
            is_combineable: None,
            max_discount_amount: None,
            max_uses: None,
            max_uses_per_customer: None,
            min_order_amount: None,
            product_ids: None,
            starts_at: None,
        }
    }
}

