/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CurrencyCode {
    #[serde(rename = "ADP")]
    Adp,
    #[serde(rename = "AED")]
    Aed,
    #[serde(rename = "AFA")]
    Afa,
    #[serde(rename = "AFN")]
    Afn,
    #[serde(rename = "ALL")]
    All,
    #[serde(rename = "AMD")]
    Amd,
    #[serde(rename = "ANG")]
    Ang,
    #[serde(rename = "AOA")]
    Aoa,
    #[serde(rename = "AOK")]
    Aok,
    #[serde(rename = "AOR")]
    Aor,
    #[serde(rename = "ARS")]
    Ars,
    #[serde(rename = "ATS")]
    Ats,
    #[serde(rename = "AUD")]
    Aud,
    #[serde(rename = "AWG")]
    Awg,
    #[serde(rename = "AZM")]
    Azm,
    #[serde(rename = "AZN")]
    Azn,
    #[serde(rename = "BAD")]
    Bad,
    #[serde(rename = "BAM")]
    Bam,
    #[serde(rename = "BBD")]
    Bbd,
    #[serde(rename = "BDT")]
    Bdt,
    #[serde(rename = "BEC")]
    Bec,
    #[serde(rename = "BEF")]
    Bef,
    #[serde(rename = "BEL")]
    Bel,
    #[serde(rename = "BGJ")]
    Bgj,
    #[serde(rename = "BGN")]
    Bgn,
    #[serde(rename = "BHD")]
    Bhd,
    #[serde(rename = "BIF")]
    Bif,
    #[serde(rename = "BMD")]
    Bmd,
    #[serde(rename = "BND")]
    Bnd,
    #[serde(rename = "BOB")]
    Bob,
    #[serde(rename = "BOV")]
    Bov,
    #[serde(rename = "BRB")]
    Brb,
    #[serde(rename = "BRL")]
    Brl,
    #[serde(rename = "BRR")]
    Brr,
    #[serde(rename = "BSD")]
    Bsd,
    #[serde(rename = "BTN")]
    Btn,
    #[serde(rename = "BWP")]
    Bwp,
    #[serde(rename = "BYB")]
    Byb,
    #[serde(rename = "BYN")]
    Byn,
    #[serde(rename = "BYR")]
    Byr,
    #[serde(rename = "BZD")]
    Bzd,
    #[serde(rename = "CAD")]
    Cad,
    #[serde(rename = "CDF")]
    Cdf,
    #[serde(rename = "CHE")]
    Che,
    #[serde(rename = "CHF")]
    Chf,
    #[serde(rename = "CHW")]
    Chw,
    #[serde(rename = "CLF")]
    Clf,
    #[serde(rename = "CLP")]
    Clp,
    #[serde(rename = "CNY")]
    Cny,
    #[serde(rename = "COP")]
    Cop,
    #[serde(rename = "COU")]
    Cou,
    #[serde(rename = "CRC")]
    Crc,
    #[serde(rename = "CSD")]
    Csd,
    #[serde(rename = "CSK")]
    Csk,
    #[serde(rename = "CUC")]
    Cuc,
    #[serde(rename = "CUP")]
    Cup,
    #[serde(rename = "CVE")]
    Cve,
    #[serde(rename = "CYP")]
    Cyp,
    #[serde(rename = "CZK")]
    Czk,
    #[serde(rename = "DDM")]
    Ddm,
    #[serde(rename = "DJF")]
    Djf,
    #[serde(rename = "DKK")]
    Dkk,
    #[serde(rename = "DOP")]
    Dop,
    #[serde(rename = "DZD")]
    Dzd,
    #[serde(rename = "ECS")]
    Ecs,
    #[serde(rename = "ECV")]
    Ecv,
    #[serde(rename = "EEK")]
    Eek,
    #[serde(rename = "EGP")]
    Egp,
    #[serde(rename = "ERN")]
    Ern,
    #[serde(rename = "ESA")]
    Esa,
    #[serde(rename = "ESB")]
    Esb,
    #[serde(rename = "ESP")]
    Esp,
    #[serde(rename = "ETB")]
    Etb,
    #[serde(rename = "EUR")]
    Eur,
    #[serde(rename = "FIM")]
    Fim,
    #[serde(rename = "FJD")]
    Fjd,
    #[serde(rename = "FKP")]
    Fkp,
    #[serde(rename = "FRF")]
    Frf,
    #[serde(rename = "GBP")]
    Gbp,
    #[serde(rename = "GEK")]
    Gek,
    #[serde(rename = "GEL")]
    Gel,
    #[serde(rename = "GHC")]
    Ghc,
    #[serde(rename = "GHP")]
    Ghp,
    #[serde(rename = "GHS")]
    Ghs,
    #[serde(rename = "GIP")]
    Gip,
    #[serde(rename = "GMD")]
    Gmd,
    #[serde(rename = "GNF")]
    Gnf,
    #[serde(rename = "GQE")]
    Gqe,
    #[serde(rename = "GRD")]
    Grd,
    #[serde(rename = "GTQ")]
    Gtq,
    #[serde(rename = "GWE")]
    Gwe,
    #[serde(rename = "GYD")]
    Gyd,
    #[serde(rename = "HKD")]
    Hkd,
    #[serde(rename = "HNL")]
    Hnl,
    #[serde(rename = "HRD")]
    Hrd,
    #[serde(rename = "HTG")]
    Htg,
    #[serde(rename = "HUF")]
    Huf,
    #[serde(rename = "IDR")]
    Idr,
    #[serde(rename = "IEP")]
    Iep,
    #[serde(rename = "ILS")]
    Ils,
    #[serde(rename = "INR")]
    Inr,
    #[serde(rename = "IQD")]
    Iqd,
    #[serde(rename = "IRR")]
    Irr,
    #[serde(rename = "ISK")]
    Isk,
    #[serde(rename = "ITL")]
    Itl,
    #[serde(rename = "JMD")]
    Jmd,
    #[serde(rename = "JOD")]
    Jod,
    #[serde(rename = "JPY")]
    Jpy,
    #[serde(rename = "KES")]
    Kes,
    #[serde(rename = "KGS")]
    Kgs,
    #[serde(rename = "KHR")]
    Khr,
    #[serde(rename = "KMF")]
    Kmf,
    #[serde(rename = "KPW")]
    Kpw,
    #[serde(rename = "KRW")]
    Krw,
    #[serde(rename = "KWD")]
    Kwd,
    #[serde(rename = "KYD")]
    Kyd,
    #[serde(rename = "KZT")]
    Kzt,
    #[serde(rename = "LAK")]
    Lak,
    #[serde(rename = "LBP")]
    Lbp,
    #[serde(rename = "LKR")]
    Lkr,
    #[serde(rename = "LRD")]
    Lrd,
    #[serde(rename = "LSL")]
    Lsl,
    #[serde(rename = "LTL")]
    Ltl,
    #[serde(rename = "LUC")]
    Luc,
    #[serde(rename = "LUF")]
    Luf,
    #[serde(rename = "LUL")]
    Lul,
    #[serde(rename = "LVL")]
    Lvl,
    #[serde(rename = "LYD")]
    Lyd,
    #[serde(rename = "MAD")]
    Mad,
    #[serde(rename = "MDL")]
    Mdl,
    #[serde(rename = "MGA")]
    Mga,
    #[serde(rename = "MGF")]
    Mgf,
    #[serde(rename = "MKD")]
    Mkd,
    #[serde(rename = "MLF")]
    Mlf,
    #[serde(rename = "MMK")]
    Mmk,
    #[serde(rename = "MNT")]
    Mnt,
    #[serde(rename = "MOP")]
    Mop,
    #[serde(rename = "MRO")]
    Mro,
    #[serde(rename = "MRU")]
    Mru,
    #[serde(rename = "MTL")]
    Mtl,
    #[serde(rename = "MUR")]
    Mur,
    #[serde(rename = "MVR")]
    Mvr,
    #[serde(rename = "MWK")]
    Mwk,
    #[serde(rename = "MXN")]
    Mxn,
    #[serde(rename = "MXV")]
    Mxv,
    #[serde(rename = "MYR")]
    Myr,
    #[serde(rename = "MZE")]
    Mze,
    #[serde(rename = "MZN")]
    Mzn,
    #[serde(rename = "NAD")]
    Nad,
    #[serde(rename = "NGN")]
    Ngn,
    #[serde(rename = "NIO")]
    Nio,
    #[serde(rename = "NLG")]
    Nlg,
    #[serde(rename = "NOK")]
    Nok,
    #[serde(rename = "NPR")]
    Npr,
    #[serde(rename = "NZD")]
    Nzd,
    #[serde(rename = "OMR")]
    Omr,
    #[serde(rename = "PAB")]
    Pab,
    #[serde(rename = "PEN")]
    Pen,
    #[serde(rename = "PGK")]
    Pgk,
    #[serde(rename = "PHP")]
    Php,
    #[serde(rename = "PKR")]
    Pkr,
    #[serde(rename = "PLN")]
    Pln,
    #[serde(rename = "PLZ")]
    Plz,
    #[serde(rename = "PTE")]
    Pte,
    #[serde(rename = "PYG")]
    Pyg,
    #[serde(rename = "QAR")]
    Qar,
    #[serde(rename = "RHD")]
    Rhd,
    #[serde(rename = "ROK")]
    Rok,
    #[serde(rename = "RON")]
    Ron,
    #[serde(rename = "RSD")]
    Rsd,
    #[serde(rename = "RUB")]
    Rub,
    #[serde(rename = "RUR")]
    Rur,
    #[serde(rename = "RWF")]
    Rwf,
    #[serde(rename = "SAR")]
    Sar,
    #[serde(rename = "SBD")]
    Sbd,
    #[serde(rename = "SCR")]
    Scr,
    #[serde(rename = "SDD")]
    Sdd,
    #[serde(rename = "SDG")]
    Sdg,
    #[serde(rename = "SEK")]
    Sek,
    #[serde(rename = "SGD")]
    Sgd,
    #[serde(rename = "SHP")]
    Shp,
    #[serde(rename = "SIT")]
    Sit,
    #[serde(rename = "SKK")]
    Skk,
    #[serde(rename = "SLE")]
    Sle,
    #[serde(rename = "SLL")]
    Sll,
    #[serde(rename = "SOS")]
    Sos,
    #[serde(rename = "SRD")]
    Srd,
    #[serde(rename = "SRG")]
    Srg,
    #[serde(rename = "SSP")]
    Ssp,
    #[serde(rename = "STD")]
    Std,
    #[serde(rename = "STN")]
    Stn,
    #[serde(rename = "SVC")]
    Svc,
    #[serde(rename = "SYP")]
    Syp,
    #[serde(rename = "SZL")]
    Szl,
    #[serde(rename = "THB")]
    Thb,
    #[serde(rename = "TJR")]
    Tjr,
    #[serde(rename = "TJS")]
    Tjs,
    #[serde(rename = "TMM")]
    Tmm,
    #[serde(rename = "TMT")]
    Tmt,
    #[serde(rename = "TND")]
    Tnd,
    #[serde(rename = "TOP")]
    Top,
    #[serde(rename = "TPE")]
    Tpe,
    #[serde(rename = "TRL")]
    Trl,
    #[serde(rename = "TRY")]
    Try,
    #[serde(rename = "TTD")]
    Ttd,
    #[serde(rename = "TWD")]
    Twd,
    #[serde(rename = "TZS")]
    Tzs,
    #[serde(rename = "UAH")]
    Uah,
    #[serde(rename = "UAK")]
    Uak,
    #[serde(rename = "UGX")]
    Ugx,
    #[serde(rename = "USD")]
    Usd,
    #[serde(rename = "USN")]
    Usn,
    #[serde(rename = "USS")]
    Uss,
    #[serde(rename = "UYI")]
    Uyi,
    #[serde(rename = "UYU")]
    Uyu,
    #[serde(rename = "UYW")]
    Uyw,
    #[serde(rename = "UZS")]
    Uzs,
    #[serde(rename = "VEB")]
    Veb,
    #[serde(rename = "VED")]
    Ved,
    #[serde(rename = "VEF")]
    Vef,
    #[serde(rename = "VES")]
    Ves,
    #[serde(rename = "VND")]
    Vnd,
    #[serde(rename = "VUV")]
    Vuv,
    #[serde(rename = "WST")]
    Wst,
    #[serde(rename = "XAD")]
    Xad,
    #[serde(rename = "XAF")]
    Xaf,
    #[serde(rename = "XAG")]
    Xag,
    #[serde(rename = "XAU")]
    Xau,
    #[serde(rename = "XBA")]
    Xba,
    #[serde(rename = "XBB")]
    Xbb,
    #[serde(rename = "XBC")]
    Xbc,
    #[serde(rename = "XBD")]
    Xbd,
    #[serde(rename = "XCD")]
    Xcd,
    #[serde(rename = "XDR")]
    Xdr,
    #[serde(rename = "XEU")]
    Xeu,
    #[serde(rename = "XOF")]
    Xof,
    #[serde(rename = "XPD")]
    Xpd,
    #[serde(rename = "XPF")]
    Xpf,
    #[serde(rename = "XPT")]
    Xpt,
    #[serde(rename = "XSU")]
    Xsu,
    #[serde(rename = "XTS")]
    Xts,
    #[serde(rename = "XUA")]
    Xua,
    #[serde(rename = "XXX")]
    Xxx,
    #[serde(rename = "YDD")]
    Ydd,
    #[serde(rename = "YER")]
    Yer,
    #[serde(rename = "YUD")]
    Yud,
    #[serde(rename = "ZAL")]
    Zal,
    #[serde(rename = "ZAR")]
    Zar,
    #[serde(rename = "ZMK")]
    Zmk,
    #[serde(rename = "ZMW")]
    Zmw,
    #[serde(rename = "ZRN")]
    Zrn,
    #[serde(rename = "ZWG")]
    Zwg,
    #[serde(rename = "ZWL")]
    Zwl,
    #[serde(rename = "ZWN")]
    Zwn,
    #[serde(rename = "ZWR")]
    Zwr,

}

impl std::fmt::Display for CurrencyCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Adp => write!(f, "ADP"),
            Self::Aed => write!(f, "AED"),
            Self::Afa => write!(f, "AFA"),
            Self::Afn => write!(f, "AFN"),
            Self::All => write!(f, "ALL"),
            Self::Amd => write!(f, "AMD"),
            Self::Ang => write!(f, "ANG"),
            Self::Aoa => write!(f, "AOA"),
            Self::Aok => write!(f, "AOK"),
            Self::Aor => write!(f, "AOR"),
            Self::Ars => write!(f, "ARS"),
            Self::Ats => write!(f, "ATS"),
            Self::Aud => write!(f, "AUD"),
            Self::Awg => write!(f, "AWG"),
            Self::Azm => write!(f, "AZM"),
            Self::Azn => write!(f, "AZN"),
            Self::Bad => write!(f, "BAD"),
            Self::Bam => write!(f, "BAM"),
            Self::Bbd => write!(f, "BBD"),
            Self::Bdt => write!(f, "BDT"),
            Self::Bec => write!(f, "BEC"),
            Self::Bef => write!(f, "BEF"),
            Self::Bel => write!(f, "BEL"),
            Self::Bgj => write!(f, "BGJ"),
            Self::Bgn => write!(f, "BGN"),
            Self::Bhd => write!(f, "BHD"),
            Self::Bif => write!(f, "BIF"),
            Self::Bmd => write!(f, "BMD"),
            Self::Bnd => write!(f, "BND"),
            Self::Bob => write!(f, "BOB"),
            Self::Bov => write!(f, "BOV"),
            Self::Brb => write!(f, "BRB"),
            Self::Brl => write!(f, "BRL"),
            Self::Brr => write!(f, "BRR"),
            Self::Bsd => write!(f, "BSD"),
            Self::Btn => write!(f, "BTN"),
            Self::Bwp => write!(f, "BWP"),
            Self::Byb => write!(f, "BYB"),
            Self::Byn => write!(f, "BYN"),
            Self::Byr => write!(f, "BYR"),
            Self::Bzd => write!(f, "BZD"),
            Self::Cad => write!(f, "CAD"),
            Self::Cdf => write!(f, "CDF"),
            Self::Che => write!(f, "CHE"),
            Self::Chf => write!(f, "CHF"),
            Self::Chw => write!(f, "CHW"),
            Self::Clf => write!(f, "CLF"),
            Self::Clp => write!(f, "CLP"),
            Self::Cny => write!(f, "CNY"),
            Self::Cop => write!(f, "COP"),
            Self::Cou => write!(f, "COU"),
            Self::Crc => write!(f, "CRC"),
            Self::Csd => write!(f, "CSD"),
            Self::Csk => write!(f, "CSK"),
            Self::Cuc => write!(f, "CUC"),
            Self::Cup => write!(f, "CUP"),
            Self::Cve => write!(f, "CVE"),
            Self::Cyp => write!(f, "CYP"),
            Self::Czk => write!(f, "CZK"),
            Self::Ddm => write!(f, "DDM"),
            Self::Djf => write!(f, "DJF"),
            Self::Dkk => write!(f, "DKK"),
            Self::Dop => write!(f, "DOP"),
            Self::Dzd => write!(f, "DZD"),
            Self::Ecs => write!(f, "ECS"),
            Self::Ecv => write!(f, "ECV"),
            Self::Eek => write!(f, "EEK"),
            Self::Egp => write!(f, "EGP"),
            Self::Ern => write!(f, "ERN"),
            Self::Esa => write!(f, "ESA"),
            Self::Esb => write!(f, "ESB"),
            Self::Esp => write!(f, "ESP"),
            Self::Etb => write!(f, "ETB"),
            Self::Eur => write!(f, "EUR"),
            Self::Fim => write!(f, "FIM"),
            Self::Fjd => write!(f, "FJD"),
            Self::Fkp => write!(f, "FKP"),
            Self::Frf => write!(f, "FRF"),
            Self::Gbp => write!(f, "GBP"),
            Self::Gek => write!(f, "GEK"),
            Self::Gel => write!(f, "GEL"),
            Self::Ghc => write!(f, "GHC"),
            Self::Ghp => write!(f, "GHP"),
            Self::Ghs => write!(f, "GHS"),
            Self::Gip => write!(f, "GIP"),
            Self::Gmd => write!(f, "GMD"),
            Self::Gnf => write!(f, "GNF"),
            Self::Gqe => write!(f, "GQE"),
            Self::Grd => write!(f, "GRD"),
            Self::Gtq => write!(f, "GTQ"),
            Self::Gwe => write!(f, "GWE"),
            Self::Gyd => write!(f, "GYD"),
            Self::Hkd => write!(f, "HKD"),
            Self::Hnl => write!(f, "HNL"),
            Self::Hrd => write!(f, "HRD"),
            Self::Htg => write!(f, "HTG"),
            Self::Huf => write!(f, "HUF"),
            Self::Idr => write!(f, "IDR"),
            Self::Iep => write!(f, "IEP"),
            Self::Ils => write!(f, "ILS"),
            Self::Inr => write!(f, "INR"),
            Self::Iqd => write!(f, "IQD"),
            Self::Irr => write!(f, "IRR"),
            Self::Isk => write!(f, "ISK"),
            Self::Itl => write!(f, "ITL"),
            Self::Jmd => write!(f, "JMD"),
            Self::Jod => write!(f, "JOD"),
            Self::Jpy => write!(f, "JPY"),
            Self::Kes => write!(f, "KES"),
            Self::Kgs => write!(f, "KGS"),
            Self::Khr => write!(f, "KHR"),
            Self::Kmf => write!(f, "KMF"),
            Self::Kpw => write!(f, "KPW"),
            Self::Krw => write!(f, "KRW"),
            Self::Kwd => write!(f, "KWD"),
            Self::Kyd => write!(f, "KYD"),
            Self::Kzt => write!(f, "KZT"),
            Self::Lak => write!(f, "LAK"),
            Self::Lbp => write!(f, "LBP"),
            Self::Lkr => write!(f, "LKR"),
            Self::Lrd => write!(f, "LRD"),
            Self::Lsl => write!(f, "LSL"),
            Self::Ltl => write!(f, "LTL"),
            Self::Luc => write!(f, "LUC"),
            Self::Luf => write!(f, "LUF"),
            Self::Lul => write!(f, "LUL"),
            Self::Lvl => write!(f, "LVL"),
            Self::Lyd => write!(f, "LYD"),
            Self::Mad => write!(f, "MAD"),
            Self::Mdl => write!(f, "MDL"),
            Self::Mga => write!(f, "MGA"),
            Self::Mgf => write!(f, "MGF"),
            Self::Mkd => write!(f, "MKD"),
            Self::Mlf => write!(f, "MLF"),
            Self::Mmk => write!(f, "MMK"),
            Self::Mnt => write!(f, "MNT"),
            Self::Mop => write!(f, "MOP"),
            Self::Mro => write!(f, "MRO"),
            Self::Mru => write!(f, "MRU"),
            Self::Mtl => write!(f, "MTL"),
            Self::Mur => write!(f, "MUR"),
            Self::Mvr => write!(f, "MVR"),
            Self::Mwk => write!(f, "MWK"),
            Self::Mxn => write!(f, "MXN"),
            Self::Mxv => write!(f, "MXV"),
            Self::Myr => write!(f, "MYR"),
            Self::Mze => write!(f, "MZE"),
            Self::Mzn => write!(f, "MZN"),
            Self::Nad => write!(f, "NAD"),
            Self::Ngn => write!(f, "NGN"),
            Self::Nio => write!(f, "NIO"),
            Self::Nlg => write!(f, "NLG"),
            Self::Nok => write!(f, "NOK"),
            Self::Npr => write!(f, "NPR"),
            Self::Nzd => write!(f, "NZD"),
            Self::Omr => write!(f, "OMR"),
            Self::Pab => write!(f, "PAB"),
            Self::Pen => write!(f, "PEN"),
            Self::Pgk => write!(f, "PGK"),
            Self::Php => write!(f, "PHP"),
            Self::Pkr => write!(f, "PKR"),
            Self::Pln => write!(f, "PLN"),
            Self::Plz => write!(f, "PLZ"),
            Self::Pte => write!(f, "PTE"),
            Self::Pyg => write!(f, "PYG"),
            Self::Qar => write!(f, "QAR"),
            Self::Rhd => write!(f, "RHD"),
            Self::Rok => write!(f, "ROK"),
            Self::Ron => write!(f, "RON"),
            Self::Rsd => write!(f, "RSD"),
            Self::Rub => write!(f, "RUB"),
            Self::Rur => write!(f, "RUR"),
            Self::Rwf => write!(f, "RWF"),
            Self::Sar => write!(f, "SAR"),
            Self::Sbd => write!(f, "SBD"),
            Self::Scr => write!(f, "SCR"),
            Self::Sdd => write!(f, "SDD"),
            Self::Sdg => write!(f, "SDG"),
            Self::Sek => write!(f, "SEK"),
            Self::Sgd => write!(f, "SGD"),
            Self::Shp => write!(f, "SHP"),
            Self::Sit => write!(f, "SIT"),
            Self::Skk => write!(f, "SKK"),
            Self::Sle => write!(f, "SLE"),
            Self::Sll => write!(f, "SLL"),
            Self::Sos => write!(f, "SOS"),
            Self::Srd => write!(f, "SRD"),
            Self::Srg => write!(f, "SRG"),
            Self::Ssp => write!(f, "SSP"),
            Self::Std => write!(f, "STD"),
            Self::Stn => write!(f, "STN"),
            Self::Svc => write!(f, "SVC"),
            Self::Syp => write!(f, "SYP"),
            Self::Szl => write!(f, "SZL"),
            Self::Thb => write!(f, "THB"),
            Self::Tjr => write!(f, "TJR"),
            Self::Tjs => write!(f, "TJS"),
            Self::Tmm => write!(f, "TMM"),
            Self::Tmt => write!(f, "TMT"),
            Self::Tnd => write!(f, "TND"),
            Self::Top => write!(f, "TOP"),
            Self::Tpe => write!(f, "TPE"),
            Self::Trl => write!(f, "TRL"),
            Self::Try => write!(f, "TRY"),
            Self::Ttd => write!(f, "TTD"),
            Self::Twd => write!(f, "TWD"),
            Self::Tzs => write!(f, "TZS"),
            Self::Uah => write!(f, "UAH"),
            Self::Uak => write!(f, "UAK"),
            Self::Ugx => write!(f, "UGX"),
            Self::Usd => write!(f, "USD"),
            Self::Usn => write!(f, "USN"),
            Self::Uss => write!(f, "USS"),
            Self::Uyi => write!(f, "UYI"),
            Self::Uyu => write!(f, "UYU"),
            Self::Uyw => write!(f, "UYW"),
            Self::Uzs => write!(f, "UZS"),
            Self::Veb => write!(f, "VEB"),
            Self::Ved => write!(f, "VED"),
            Self::Vef => write!(f, "VEF"),
            Self::Ves => write!(f, "VES"),
            Self::Vnd => write!(f, "VND"),
            Self::Vuv => write!(f, "VUV"),
            Self::Wst => write!(f, "WST"),
            Self::Xad => write!(f, "XAD"),
            Self::Xaf => write!(f, "XAF"),
            Self::Xag => write!(f, "XAG"),
            Self::Xau => write!(f, "XAU"),
            Self::Xba => write!(f, "XBA"),
            Self::Xbb => write!(f, "XBB"),
            Self::Xbc => write!(f, "XBC"),
            Self::Xbd => write!(f, "XBD"),
            Self::Xcd => write!(f, "XCD"),
            Self::Xdr => write!(f, "XDR"),
            Self::Xeu => write!(f, "XEU"),
            Self::Xof => write!(f, "XOF"),
            Self::Xpd => write!(f, "XPD"),
            Self::Xpf => write!(f, "XPF"),
            Self::Xpt => write!(f, "XPT"),
            Self::Xsu => write!(f, "XSU"),
            Self::Xts => write!(f, "XTS"),
            Self::Xua => write!(f, "XUA"),
            Self::Xxx => write!(f, "XXX"),
            Self::Ydd => write!(f, "YDD"),
            Self::Yer => write!(f, "YER"),
            Self::Yud => write!(f, "YUD"),
            Self::Zal => write!(f, "ZAL"),
            Self::Zar => write!(f, "ZAR"),
            Self::Zmk => write!(f, "ZMK"),
            Self::Zmw => write!(f, "ZMW"),
            Self::Zrn => write!(f, "ZRN"),
            Self::Zwg => write!(f, "ZWG"),
            Self::Zwl => write!(f, "ZWL"),
            Self::Zwn => write!(f, "ZWN"),
            Self::Zwr => write!(f, "ZWR"),
        }
    }
}

impl Default for CurrencyCode {
    fn default() -> CurrencyCode {
        Self::Adp
    }
}

