/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeliverableResponse {
    #[serde(rename = "availableStock")]
    pub available_stock: i64,
    #[serde(rename = "deliverableQuantity")]
    pub deliverable_quantity: i64,
    #[serde(rename = "maxSellable", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_sellable: Option<Option<i64>>,
    #[serde(rename = "productId")]
    pub product_id: uuid::Uuid,
    #[serde(rename = "reservedStock")]
    pub reserved_stock: i64,
    #[serde(rename = "warehouseId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub warehouse_id: Option<Option<String>>,
}

impl DeliverableResponse {
    pub fn new(available_stock: i64, deliverable_quantity: i64, product_id: uuid::Uuid, reserved_stock: i64) -> DeliverableResponse {
        DeliverableResponse {
            available_stock,
            deliverable_quantity,
            max_sellable: None,
            product_id,
            reserved_stock,
            warehouse_id: None,
        }
    }
}

