/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeliveryNote {
    #[serde(rename = "address", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub address: Option<Option<serde_json::Value>>,
    /// References the contact entity.
    #[serde(rename = "contactId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub contact_id: Option<Option<String>>,
    #[serde(rename = "contactName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub contact_name: Option<Option<String>>,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "deliveryDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub delivery_date: Option<Option<chrono::NaiveDate>>,
    #[serde(rename = "deliveryNoteNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub delivery_note_number: Option<Option<String>>,
    #[serde(rename = "files", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub files: Option<Option<serde_json::Value>>,
    #[serde(rename = "introduction", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub introduction: Option<Option<String>>,
    #[serde(rename = "lineItems", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub line_items: Option<Option<serde_json::Value>>,
    /// References the preceding sales voucher entity.
    #[serde(rename = "precedingSalesVoucherId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub preceding_sales_voucher_id: Option<Option<String>>,
    #[serde(rename = "precedingSalesVoucherType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub preceding_sales_voucher_type: Option<Option<models::PrecedingSalesVoucherType>>,
    #[serde(rename = "remark", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub remark: Option<Option<String>>,
    #[serde(rename = "shippingDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub shipping_date: Option<Option<chrono::NaiveDate>>,
    #[serde(rename = "shippingMethod", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub shipping_method: Option<Option<String>>,
    #[serde(rename = "subtotal", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subtotal: Option<Option<String>>,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "totalAmount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_amount: Option<Option<String>>,
    #[serde(rename = "voucherDate")]
    pub voucher_date: chrono::NaiveDate,
    #[serde(rename = "voucherStatus")]
    pub voucher_status: models::VoucherStatus,
}

impl DeliveryNote {
    pub fn new(currency: String, voucher_date: chrono::NaiveDate, voucher_status: models::VoucherStatus) -> DeliveryNote {
        DeliveryNote {
            address: None,
            contact_id: None,
            contact_name: None,
            currency,
            delivery_date: None,
            delivery_note_number: None,
            files: None,
            introduction: None,
            line_items: None,
            preceding_sales_voucher_id: None,
            preceding_sales_voucher_type: None,
            remark: None,
            shipping_date: None,
            shipping_method: None,
            subtotal: None,
            title: None,
            total_amount: None,
            voucher_date,
            voucher_status,
        }
    }
}

