/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeliveryAppointmentCreate {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "notes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Option<String>>,
    #[serde(rename = "phone", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub phone: Option<Option<String>>,
    #[serde(rename = "requestedDate")]
    pub requested_date: chrono::NaiveDate,
    /// One of: requested | confirmed | arrived | cancelled | completed
    #[serde(rename = "status")]
    pub status: models::DeliveryAppointmentStatus,
    #[serde(rename = "supplierName")]
    pub supplier_name: String,
    /// e.g. \"08:00-10:00\"
    #[serde(rename = "timeSlot", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub time_slot: Option<Option<String>>,
    /// References the warehouse entity.
    #[serde(rename = "warehouseId")]
    pub warehouse_id: String,
}

impl DeliveryAppointmentCreate {
    pub fn new(email: String, requested_date: chrono::NaiveDate, status: models::DeliveryAppointmentStatus, supplier_name: String, warehouse_id: String) -> DeliveryAppointmentCreate {
        DeliveryAppointmentCreate {
            email,
            notes: None,
            phone: None,
            requested_date,
            status,
            supplier_name,
            time_slot: None,
            warehouse_id,
        }
    }
}

