/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DownPaymentInvoice {
    #[serde(rename = "contact_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub contact_id: Option<Option<String>>,
    #[serde(rename = "contact_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub contact_name: Option<Option<String>>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "notes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Option<String>>,
    #[serde(rename = "paid_amount")]
    pub paid_amount: String,
    #[serde(rename = "total_amount")]
    pub total_amount: String,
    #[serde(rename = "voucher_date")]
    pub voucher_date: chrono::NaiveDate,
    #[serde(rename = "voucher_number", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub voucher_number: Option<Option<String>>,
    #[serde(rename = "voucher_status")]
    pub voucher_status: String,
}

impl DownPaymentInvoice {
    pub fn new(created_at: String, currency: String, id: String, paid_amount: String, total_amount: String, voucher_date: chrono::NaiveDate, voucher_status: String) -> DownPaymentInvoice {
        DownPaymentInvoice {
            contact_id: None,
            contact_name: None,
            created_at,
            currency,
            id,
            notes: None,
            paid_amount,
            total_amount,
            voucher_date,
            voucher_number: None,
            voucher_status,
        }
    }
}

