/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EksErgebnis {
    #[serde(rename = "gesamtergebnis")]
    pub gesamtergebnis: String,
    #[serde(rename = "monate")]
    pub monate: Vec<models::EksMonatsWert>,
    #[serde(rename = "prognose_naechste_6_monate")]
    pub prognose_naechste_6_monate: String,
    #[serde(rename = "summe_ausgaben")]
    pub summe_ausgaben: String,
    #[serde(rename = "summe_einnahmen")]
    pub summe_einnahmen: String,
    #[serde(rename = "zeitraum_bis")]
    pub zeitraum_bis: String,
    #[serde(rename = "zeitraum_von")]
    pub zeitraum_von: String,
}

impl EksErgebnis {
    pub fn new(gesamtergebnis: String, monate: Vec<models::EksMonatsWert>, prognose_naechste_6_monate: String, summe_ausgaben: String, summe_einnahmen: String, zeitraum_bis: String, zeitraum_von: String) -> EksErgebnis {
        EksErgebnis {
            gesamtergebnis,
            monate,
            prognose_naechste_6_monate,
            summe_ausgaben,
            summe_einnahmen,
            zeitraum_bis,
            zeitraum_von,
        }
    }
}

