/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailTemplate {
    /// E-mail body with optional placeholders.
    #[serde(rename = "body")]
    pub body: String,
    /// Human-readable template name, e.g. \"Follow-up after quote\".
    #[serde(rename = "name")]
    pub name: String,
    /// One of: active | inactive
    #[serde(rename = "status")]
    pub status: models::EmailTemplateStatus,
    /// E-mail subject line with optional placeholders.
    #[serde(rename = "subject")]
    pub subject: String,
    /// Placeholders used by this template, e.g. `[\"contact.first_name\"]`.
    #[serde(rename = "variables", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub variables: Option<Option<serde_json::Value>>,
}

impl EmailTemplate {
    pub fn new(body: String, name: String, status: models::EmailTemplateStatus, subject: String) -> EmailTemplate {
        EmailTemplate {
            body,
            name,
            status,
            subject,
            variables: None,
        }
    }
}

