/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailTemplateUpdate {
    /// E-mail body with optional placeholders.
    #[serde(rename = "body", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub body: Option<Option<String>>,
    /// Human-readable template name, e.g. \"Follow-up after quote\".
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    /// One of: active | inactive
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<models::EmailTemplateStatus>>,
    /// E-mail subject line with optional placeholders.
    #[serde(rename = "subject", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subject: Option<Option<String>>,
    /// Placeholders used by this template, e.g. `[\"contact.first_name\"]`.
    #[serde(rename = "variables", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub variables: Option<Option<serde_json::Value>>,
}

impl EmailTemplateUpdate {
    pub fn new() -> EmailTemplateUpdate {
        EmailTemplateUpdate {
            body: None,
            name: None,
            status: None,
            subject: None,
            variables: None,
        }
    }
}

