/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmissionEntry {
    /// Activity amount in `unit` (kWh, l, km, t, tkm, EUR).
    #[serde(rename = "activityValue")]
    pub activity_value: String,
    /// GHG-Protocol category key, e.g. \"purchased_goods\", \"business_travel\".
    #[serde(rename = "categoryId")]
    pub category_id: String,
    #[serde(rename = "description")]
    pub description: String,
    /// Emission-factor source, e.g. \"UBA-2024\", \"DEFRA-2024\".
    #[serde(rename = "efSource")]
    pub ef_source: String,
    #[serde(rename = "efVersion")]
    pub ef_version: String,
    /// \"activity\" | \"spend\" | \"supplier\".
    #[serde(rename = "method")]
    pub method: models::EmissionMethod,
    /// GHG scope: \"1\" | \"2\" | \"3\".
    #[serde(rename = "scope")]
    pub scope: models::GhgScope,
    /// Computed server-side: activity * factor / 1000, rounded to 4 dp.
    #[serde(rename = "tco2e")]
    pub tco2e: String,
    /// Unit of the activity value.
    #[serde(rename = "unit")]
    pub unit: String,
    #[serde(rename = "updatedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// Reporting year.
    #[serde(rename = "year")]
    pub year: i32,
}

impl EmissionEntry {
    pub fn new(activity_value: String, category_id: String, description: String, ef_source: String, ef_version: String, method: models::EmissionMethod, scope: models::GhgScope, tco2e: String, unit: String, year: i32) -> EmissionEntry {
        EmissionEntry {
            activity_value,
            category_id,
            description,
            ef_source,
            ef_version,
            method,
            scope,
            tco2e,
            unit,
            updated_at: None,
            year,
        }
    }
}

