/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EuerZeile {
    #[serde(rename = "abschnitt")]
    pub abschnitt: String,
    #[serde(rename = "betrag")]
    pub betrag: String,
    #[serde(rename = "bezeichnung")]
    pub bezeichnung: String,
    #[serde(rename = "zeile")]
    pub zeile: i32,
}

impl EuerZeile {
    pub fn new(abschnitt: String, betrag: String, bezeichnung: String, zeile: i32) -> EuerZeile {
        EuerZeile {
            abschnitt,
            betrag,
            bezeichnung,
            zeile,
        }
    }
}

