/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GenerateCountRequest : Body for the cycle-count generator: create a draft count document for a warehouse, optionally restricted to a set of product ids.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenerateCountRequest {
    #[serde(rename = "notes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Option<String>>,
    #[serde(rename = "productIds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub product_ids: Option<Option<Vec<uuid::Uuid>>>,
    #[serde(rename = "warehouseId")]
    pub warehouse_id: String,
}

impl GenerateCountRequest {
    /// Body for the cycle-count generator: create a draft count document for a warehouse, optionally restricted to a set of product ids.
    pub fn new(warehouse_id: String) -> GenerateCountRequest {
        GenerateCountRequest {
            notes: None,
            product_ids: None,
            warehouse_id,
        }
    }
}

