/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GewinnverwendungsReport {
    /// Bilanzgewinn nach Einstellung (§ 174 AktG, Beschluss der HV).
    #[serde(rename = "bilanzgewinn")]
    pub bilanzgewinn: String,
    #[serde(rename = "gesetzliche_ruecklage_bestand")]
    pub gesetzliche_ruecklage_bestand: String,
    /// Deckel: 10 % des Grundkapitals (§ 150 Abs. 2 AktG).
    #[serde(rename = "gesetzliche_ruecklage_cap")]
    pub gesetzliche_ruecklage_cap: String,
    /// Rücklage nach Einstellung.
    #[serde(rename = "gesetzliche_ruecklage_nach")]
    pub gesetzliche_ruecklage_nach: String,
    /// Vorgeschlagene Einstellung in die gesetzliche Rücklage (§ 150 Abs. 2 AktG).
    #[serde(rename = "gesetzliche_ruecklage_soll")]
    pub gesetzliche_ruecklage_soll: String,
    #[serde(rename = "gezeichnetes_kapital")]
    pub gezeichnetes_kapital: String,
    #[serde(rename = "jahresueberschuss")]
    pub jahresueberschuss: String,
    #[serde(rename = "year")]
    pub year: i32,
    #[serde(rename = "zeilen")]
    pub zeilen: Vec<models::GewinnverwendungsZeile>,
}

impl GewinnverwendungsReport {
    pub fn new(bilanzgewinn: String, gesetzliche_ruecklage_bestand: String, gesetzliche_ruecklage_cap: String, gesetzliche_ruecklage_nach: String, gesetzliche_ruecklage_soll: String, gezeichnetes_kapital: String, jahresueberschuss: String, year: i32, zeilen: Vec<models::GewinnverwendungsZeile>) -> GewinnverwendungsReport {
        GewinnverwendungsReport {
            bilanzgewinn,
            gesetzliche_ruecklage_bestand,
            gesetzliche_ruecklage_cap,
            gesetzliche_ruecklage_nach,
            gesetzliche_ruecklage_soll,
            gezeichnetes_kapital,
            jahresueberschuss,
            year,
            zeilen,
        }
    }
}

