/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GoodsReceipt {
    #[serde(rename = "grNumber")]
    pub gr_number: String,
    /// JSON array of `{product_id, name, quantity, batch_number?, expiry_date?, bin_location?}`.
    #[serde(rename = "lineItems", deserialize_with = "Option::deserialize")]
    pub line_items: Option<serde_json::Value>,
    #[serde(rename = "notes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Option<String>>,
    /// References the purchase order entity.
    #[serde(rename = "purchaseOrderId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub purchase_order_id: Option<Option<String>>,
    #[serde(rename = "receiptDate")]
    pub receipt_date: chrono::NaiveDate,
    /// References the supplier entity.
    #[serde(rename = "supplierContactId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub supplier_contact_id: Option<Option<String>>,
    #[serde(rename = "supplierName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub supplier_name: Option<Option<String>>,
    /// References the warehouse entity.
    #[serde(rename = "warehouseId")]
    pub warehouse_id: String,
}

impl GoodsReceipt {
    pub fn new(gr_number: String, line_items: Option<serde_json::Value>, receipt_date: chrono::NaiveDate, warehouse_id: String) -> GoodsReceipt {
        GoodsReceipt {
            gr_number,
            line_items,
            notes: None,
            purchase_order_id: None,
            receipt_date,
            supplier_contact_id: None,
            supplier_name: None,
            warehouse_id,
        }
    }
}

