/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InstituteProfileUpdate : Partial update of the institute profile.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstituteProfileUpdate {
    #[serde(rename = "instituteType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub institute_type: Option<Option<String>>,
    #[serde(rename = "kapitalmarktorientiert", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub kapitalmarktorientiert: Option<Option<bool>>,
}

impl InstituteProfileUpdate {
    /// Partial update of the institute profile.
    pub fn new() -> InstituteProfileUpdate {
        InstituteProfileUpdate {
            institute_type: None,
            kapitalmarktorientiert: None,
        }
    }
}

