/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstituteStatus {
    #[serde(rename = "checklist")]
    pub checklist: Vec<models::InstituteCheckItem>,
    #[serde(rename = "deadlines")]
    pub deadlines: Box<models::InstituteDeadlines>,
    #[serde(rename = "instituteType")]
    pub institute_type: String,
    #[serde(rename = "kapitalmarktorientiert")]
    pub kapitalmarktorientiert: bool,
}

impl InstituteStatus {
    pub fn new(checklist: Vec<models::InstituteCheckItem>, deadlines: models::InstituteDeadlines, institute_type: String, kapitalmarktorientiert: bool) -> InstituteStatus {
        InstituteStatus {
            checklist,
            deadlines: Box::new(deadlines),
            institute_type,
            kapitalmarktorientiert,
        }
    }
}

