/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InventoryCountUpdate {
    #[serde(rename = "countDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub count_date: Option<Option<chrono::NaiveDate>>,
    #[serde(rename = "countNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub count_number: Option<Option<String>>,
    /// JSON array of `{product_id, name, sku, expected_quantity, counted_quantity, bin_location?, batch_number?, variance}`.
    #[serde(rename = "lineItems", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub line_items: Option<Option<serde_json::Value>>,
    #[serde(rename = "notes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Option<String>>,
    /// One of: draft | counting | reviewed | posted
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<models::InventoryCountStatus>>,
    /// References the warehouse entity.
    #[serde(rename = "warehouseId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub warehouse_id: Option<Option<String>>,
}

impl InventoryCountUpdate {
    pub fn new() -> InventoryCountUpdate {
        InventoryCountUpdate {
            count_date: None,
            count_number: None,
            line_items: None,
            notes: None,
            status: None,
            warehouse_id: None,
        }
    }
}

