/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InventoryCountCreate {
    #[serde(rename = "countDate")]
    pub count_date: chrono::NaiveDate,
    #[serde(rename = "countNumber")]
    pub count_number: String,
    /// JSON array of `{product_id, name, sku, expected_quantity, counted_quantity, bin_location?, batch_number?, variance}`.
    #[serde(rename = "lineItems", deserialize_with = "Option::deserialize")]
    pub line_items: Option<serde_json::Value>,
    #[serde(rename = "notes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Option<String>>,
    /// One of: draft | counting | reviewed | posted
    #[serde(rename = "status")]
    pub status: models::InventoryCountStatus,
    /// References the warehouse entity.
    #[serde(rename = "warehouseId")]
    pub warehouse_id: String,
}

impl InventoryCountCreate {
    pub fn new(count_date: chrono::NaiveDate, count_number: String, line_items: Option<serde_json::Value>, status: models::InventoryCountStatus, warehouse_id: String) -> InventoryCountCreate {
        InventoryCountCreate {
            count_date,
            count_number,
            line_items,
            notes: None,
            status,
            warehouse_id,
        }
    }
}

