/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InvoiceStatus {
    #[serde(rename = "Draft")]
    Draft,
    #[serde(rename = "Sent")]
    Sent,
    #[serde(rename = "PartiallyPaid")]
    PartiallyPaid,
    #[serde(rename = "Paid")]
    Paid,
    #[serde(rename = "Overdue")]
    Overdue,
    #[serde(rename = "Cancelled")]
    Cancelled,
    #[serde(rename = "Credited")]
    Credited,
    #[serde(rename = "Expired")]
    Expired,
    #[serde(rename = "Dunning")]
    Dunning,
    #[serde(rename = "CollectDebt")]
    CollectDebt,

}

impl std::fmt::Display for InvoiceStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Draft => write!(f, "Draft"),
            Self::Sent => write!(f, "Sent"),
            Self::PartiallyPaid => write!(f, "PartiallyPaid"),
            Self::Paid => write!(f, "Paid"),
            Self::Overdue => write!(f, "Overdue"),
            Self::Cancelled => write!(f, "Cancelled"),
            Self::Credited => write!(f, "Credited"),
            Self::Expired => write!(f, "Expired"),
            Self::Dunning => write!(f, "Dunning"),
            Self::CollectDebt => write!(f, "CollectDebt"),
        }
    }
}

impl Default for InvoiceStatus {
    fn default() -> InvoiceStatus {
        Self::Draft
    }
}

