/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JahresUstErgebnis {
    #[serde(rename = "bis")]
    pub bis: String,
    #[serde(rename = "gespeicherte_perioden")]
    pub gespeicherte_perioden: i32,
    #[serde(rename = "hat_ig_transaktionen")]
    pub hat_ig_transaktionen: bool,
    #[serde(rename = "ist_kleinunternehmer")]
    pub ist_kleinunternehmer: bool,
    #[serde(rename = "jahr")]
    pub jahr: i32,
    #[serde(rename = "kz_41")]
    pub kz_41: String,
    #[serde(rename = "kz_43")]
    pub kz_43: String,
    #[serde(rename = "kz_46")]
    pub kz_46: String,
    #[serde(rename = "kz_47")]
    pub kz_47: String,
    #[serde(rename = "kz_48")]
    pub kz_48: String,
    #[serde(rename = "kz_61")]
    pub kz_61: String,
    #[serde(rename = "kz_66")]
    pub kz_66: String,
    #[serde(rename = "kz_67")]
    pub kz_67: String,
    #[serde(rename = "kz_81")]
    pub kz_81: String,
    #[serde(rename = "kz_83")]
    pub kz_83: String,
    #[serde(rename = "kz_84")]
    pub kz_84: String,
    #[serde(rename = "kz_85")]
    pub kz_85: String,
    #[serde(rename = "kz_86")]
    pub kz_86: String,
    #[serde(rename = "kz_88")]
    pub kz_88: String,
    #[serde(rename = "kz_89")]
    pub kz_89: String,
    #[serde(rename = "kz_93")]
    pub kz_93: String,
    #[serde(rename = "restschuld")]
    pub restschuld: String,
    #[serde(rename = "summe_vorauszahlungen")]
    pub summe_vorauszahlungen: String,
    #[serde(rename = "von")]
    pub von: String,
    #[serde(rename = "zahllast")]
    pub zahllast: String,
}

impl JahresUstErgebnis {
    pub fn new(bis: String, gespeicherte_perioden: i32, hat_ig_transaktionen: bool, ist_kleinunternehmer: bool, jahr: i32, kz_41: String, kz_43: String, kz_46: String, kz_47: String, kz_48: String, kz_61: String, kz_66: String, kz_67: String, kz_81: String, kz_83: String, kz_84: String, kz_85: String, kz_86: String, kz_88: String, kz_89: String, kz_93: String, restschuld: String, summe_vorauszahlungen: String, von: String, zahllast: String) -> JahresUstErgebnis {
        JahresUstErgebnis {
            bis,
            gespeicherte_perioden,
            hat_ig_transaktionen,
            ist_kleinunternehmer,
            jahr,
            kz_41,
            kz_43,
            kz_46,
            kz_47,
            kz_48,
            kz_61,
            kz_66,
            kz_67,
            kz_81,
            kz_83,
            kz_84,
            kz_85,
            kz_86,
            kz_88,
            kz_89,
            kz_93,
            restschuld,
            summe_vorauszahlungen,
            von,
            zahllast,
        }
    }
}

