/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobTitleGap {
    #[serde(rename = "employee_count")]
    pub employee_count: i32,
    #[serde(rename = "female_mean_hourly")]
    pub female_mean_hourly: String,
    #[serde(rename = "job_title")]
    pub job_title: String,
    #[serde(rename = "male_mean_hourly")]
    pub male_mean_hourly: String,
    #[serde(rename = "mean_gap_pct")]
    pub mean_gap_pct: f64,
    #[serde(rename = "median_gap_pct")]
    pub median_gap_pct: f64,
}

impl JobTitleGap {
    pub fn new(employee_count: i32, female_mean_hourly: String, job_title: String, male_mean_hourly: String, mean_gap_pct: f64, median_gap_pct: f64) -> JobTitleGap {
        JobTitleGap {
            employee_count,
            female_mean_hourly,
            job_title,
            male_mean_hourly,
            mean_gap_pct,
            median_gap_pct,
        }
    }
}

