/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobPostingUpdate {
    #[serde(rename = "currency", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub currency: Option<Option<String>>,
    #[serde(rename = "department", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub department: Option<Option<String>>,
    /// What the job is; markdown/HTML.
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// full_time | part_time | contract | internship | temporary
    #[serde(rename = "employmentType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub employment_type: Option<Option<models::EmploymentType>>,
    #[serde(rename = "location", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub location: Option<Option<String>>,
    #[serde(rename = "remote", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub remote: Option<Option<bool>>,
    /// List of required skill names (JSON array of strings).
    #[serde(rename = "requiredSkills", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub required_skills: Option<Option<serde_json::Value>>,
    /// Structured profile of the required candidate (skills, experience).
    #[serde(rename = "requirements", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub requirements: Option<Option<String>>,
    #[serde(rename = "salaryMax", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub salary_max: Option<Option<i32>>,
    #[serde(rename = "salaryMin", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub salary_min: Option<Option<i32>>,
    /// draft | published | closed
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<models::JobPostingStatus>>,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
}

impl JobPostingUpdate {
    pub fn new() -> JobPostingUpdate {
        JobPostingUpdate {
            currency: None,
            department: None,
            description: None,
            employment_type: None,
            location: None,
            remote: None,
            required_skills: None,
            requirements: None,
            salary_max: None,
            salary_min: None,
            status: None,
            title: None,
        }
    }
}

