/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KycRecordCreate {
    /// Referenz auf den Kunden/Kontakt.
    #[serde(rename = "customerId", skip_serializing_if = "Option::is_none")]
    pub customer_id: Option<String>,
    /// Name des Kunden (für die Suche).
    #[serde(rename = "customerName", skip_serializing_if = "Option::is_none")]
    pub customer_name: Option<String>,
    /// Datum der KYC-Prüfung (GwG § 8).
    #[serde(rename = "kycDate", skip_serializing_if = "Option::is_none")]
    pub kyc_date: Option<chrono::NaiveDate>,
    /// Freitext-Notizen.
    #[serde(rename = "notes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Option<String>>,
    /// Aufbewahrungsfrist (GwG § 8 Abs. 4: 5 Jahre).
    #[serde(rename = "retentionUntil", skip_serializing_if = "Option::is_none")]
    pub retention_until: Option<chrono::NaiveDate>,
    /// Risikoeinschätzung (z. B. Risikoklasse).
    #[serde(rename = "riskAssessment", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub risk_assessment: Option<Option<String>>,
}

impl KycRecordCreate {
    pub fn new() -> KycRecordCreate {
        KycRecordCreate {
            customer_id: None,
            customer_name: None,
            kyc_date: None,
            notes: None,
            retention_until: None,
            risk_assessment: None,
        }
    }
}

