/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LegalDocType : Legal document type (matches `DOC_TYPES` in legal_defaults.rs).
/// Legal document type (matches `DOC_TYPES` in legal_defaults.rs).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LegalDocType {
    #[serde(rename = "imprint")]
    Imprint,
    #[serde(rename = "privacy")]
    Privacy,
    #[serde(rename = "terms")]
    Terms,
    #[serde(rename = "withdrawal")]
    Withdrawal,
    #[serde(rename = "refund")]
    Refund,
    #[serde(rename = "shipping")]
    Shipping,
    #[serde(rename = "gpsr")]
    Gpsr,
    #[serde(rename = "cookie_notice")]
    CookieNotice,

}

impl std::fmt::Display for LegalDocType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Imprint => write!(f, "imprint"),
            Self::Privacy => write!(f, "privacy"),
            Self::Terms => write!(f, "terms"),
            Self::Withdrawal => write!(f, "withdrawal"),
            Self::Refund => write!(f, "refund"),
            Self::Shipping => write!(f, "shipping"),
            Self::Gpsr => write!(f, "gpsr"),
            Self::CookieNotice => write!(f, "cookie_notice"),
        }
    }
}

impl Default for LegalDocType {
    fn default() -> LegalDocType {
        Self::Imprint
    }
}

