/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LiquidityPosition {
    #[serde(rename = "accounts_payable")]
    pub accounts_payable: f64,
    #[serde(rename = "accounts_receivable")]
    pub accounts_receivable: f64,
    #[serde(rename = "cash_and_equivalents")]
    pub cash_and_equivalents: f64,
    #[serde(rename = "current_ratio")]
    pub current_ratio: f64,
    #[serde(rename = "quick_ratio")]
    pub quick_ratio: f64,
    #[serde(rename = "working_capital")]
    pub working_capital: f64,
}

impl LiquidityPosition {
    pub fn new(accounts_payable: f64, accounts_receivable: f64, cash_and_equivalents: f64, current_ratio: f64, quick_ratio: f64, working_capital: f64) -> LiquidityPosition {
        LiquidityPosition {
            accounts_payable,
            accounts_receivable,
            cash_and_equivalents,
            current_ratio,
            quick_ratio,
            working_capital,
        }
    }
}

