/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model {
    #[serde(rename = "backup_codes")]
    pub backup_codes: Vec<String>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "deleted_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "email_verified")]
    pub email_verified: bool,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "is_totp_enabled")]
    pub is_totp_enabled: bool,
    #[serde(rename = "last_login", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_login: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "oauth_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub oauth_id: Option<Option<String>>,
    #[serde(rename = "oauth_provider", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub oauth_provider: Option<Option<String>>,
    /// Set on password change; auth/refresh tokens issued before this timestamp are rejected by the auth middleware.
    #[serde(rename = "password_changed_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub password_changed_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "password_hash")]
    pub password_hash: String,
    #[serde(rename = "picture", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub picture: Option<Option<String>>,
    /// When the user accepted the data privacy policy (GDPR consent record).
    #[serde(rename = "privacy_accepted_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub privacy_accepted_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "totp_secret", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub totp_secret: Option<Option<String>>,
    #[serde(rename = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl Model {
    pub fn new(backup_codes: Vec<String>, created_at: chrono::DateTime<chrono::FixedOffset>, email: String, email_verified: bool, id: uuid::Uuid, is_active: bool, is_totp_enabled: bool, name: String, password_hash: String, updated_at: chrono::DateTime<chrono::FixedOffset>) -> Model {
        Model {
            backup_codes,
            created_at,
            deleted_at: None,
            email,
            email_verified,
            id,
            is_active,
            is_totp_enabled,
            last_login: None,
            name,
            oauth_id: None,
            oauth_provider: None,
            password_changed_at: None,
            password_hash,
            picture: None,
            privacy_accepted_at: None,
            totp_secret: None,
            updated_at,
        }
    }
}

