/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MovementType : Stock movement type.
/// Stock movement type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MovementType {
    #[serde(rename = "goods_receipt")]
    GoodsReceipt,
    #[serde(rename = "goods_receipt_reversal")]
    GoodsReceiptReversal,
    #[serde(rename = "transfer_in")]
    TransferIn,
    #[serde(rename = "transfer_out")]
    TransferOut,
    #[serde(rename = "return_restock")]
    ReturnRestock,
    #[serde(rename = "production_consumption")]
    ProductionConsumption,
    #[serde(rename = "production_completion")]
    ProductionCompletion,
    #[serde(rename = "inventory_adjustment")]
    InventoryAdjustment,
    #[serde(rename = "sale")]
    Sale,
    #[serde(rename = "other")]
    Other,

}

impl std::fmt::Display for MovementType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::GoodsReceipt => write!(f, "goods_receipt"),
            Self::GoodsReceiptReversal => write!(f, "goods_receipt_reversal"),
            Self::TransferIn => write!(f, "transfer_in"),
            Self::TransferOut => write!(f, "transfer_out"),
            Self::ReturnRestock => write!(f, "return_restock"),
            Self::ProductionConsumption => write!(f, "production_consumption"),
            Self::ProductionCompletion => write!(f, "production_completion"),
            Self::InventoryAdjustment => write!(f, "inventory_adjustment"),
            Self::Sale => write!(f, "sale"),
            Self::Other => write!(f, "other"),
        }
    }
}

impl Default for MovementType {
    fn default() -> MovementType {
        Self::GoodsReceipt
    }
}

