/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParticipationCreate {
    /// Datum des Erwerbs der Beteiligung.
    #[serde(rename = "acquiredAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub acquired_at: Option<Option<chrono::NaiveDate>>,
    /// Bestellungsrecht für Geschäftsführung/Aufsichtsrat (§ 290 Abs. 2 Nr. 2 HGB).
    #[serde(rename = "boardAppointment", skip_serializing_if = "Option::is_none")]
    pub board_appointment: Option<bool>,
    /// Name des Beteiligungsunternehmens (§ 271 HGB).
    #[serde(rename = "companyName", skip_serializing_if = "Option::is_none")]
    pub company_name: Option<String>,
    /// Beherrschungsvertrag (§ 290 Abs. 2 Nr. 3 HGB).
    #[serde(rename = "controlAgreement", skip_serializing_if = "Option::is_none")]
    pub control_agreement: Option<bool>,
    /// Rechtsform, z. B. \"GmbH\".
    #[serde(rename = "legalForm", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub legal_form: Option<Option<String>>,
    /// Anteilsquote in Prozent (§ 271 HGB; > 20 % widerlegbare Vermutung).
    #[serde(rename = "ownershipPct", skip_serializing_if = "Option::is_none")]
    pub ownership_pct: Option<String>,
    /// Zweckgesellschaft (§ 290 Abs. 2 Nr. 4 HGB).
    #[serde(rename = "purposeVehicle", skip_serializing_if = "Option::is_none")]
    pub purpose_vehicle: Option<bool>,
    /// Stimmrechtsmehrheit (§ 290 Abs. 2 Nr. 1 HGB).
    #[serde(rename = "votingMajority", skip_serializing_if = "Option::is_none")]
    pub voting_majority: Option<bool>,
}

impl ParticipationCreate {
    pub fn new() -> ParticipationCreate {
        ParticipationCreate {
            acquired_at: None,
            board_appointment: None,
            company_name: None,
            control_agreement: None,
            legal_form: None,
            ownership_pct: None,
            purpose_vehicle: None,
            voting_majority: None,
        }
    }
}

