/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PayrollAutopayPayload {
    #[serde(rename = "debtor_bic", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub debtor_bic: Option<Option<String>>,
    #[serde(rename = "debtor_iban", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub debtor_iban: Option<Option<String>>,
    #[serde(rename = "debtor_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub debtor_name: Option<Option<String>>,
    #[serde(rename = "execution_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub execution_date: Option<Option<chrono::NaiveDate>>,
}

impl PayrollAutopayPayload {
    pub fn new() -> PayrollAutopayPayload {
        PayrollAutopayPayload {
            debtor_bic: None,
            debtor_iban: None,
            debtor_name: None,
            execution_date: None,
        }
    }
}

