/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PayrollEntryApi {
    #[serde(rename = "av_employee")]
    pub av_employee: String,
    #[serde(rename = "av_employer")]
    pub av_employer: String,
    #[serde(rename = "church_tax_amount")]
    pub church_tax_amount: String,
    #[serde(rename = "employee", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub employee: Option<Option<Box<models::Employee>>>,
    #[serde(rename = "employee_id")]
    pub employee_id: uuid::Uuid,
    #[serde(rename = "entry_id")]
    pub entry_id: uuid::Uuid,
    #[serde(rename = "extra_payment_reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub extra_payment_reason: Option<Option<String>>,
    #[serde(rename = "extra_payments")]
    pub extra_payments: String,
    #[serde(rename = "gross_salary")]
    pub gross_salary: String,
    #[serde(rename = "kv_employee")]
    pub kv_employee: String,
    #[serde(rename = "kv_employer")]
    pub kv_employer: String,
    #[serde(rename = "lohnsteuer")]
    pub lohnsteuer: String,
    #[serde(rename = "net_salary")]
    pub net_salary: String,
    #[serde(rename = "notes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Option<String>>,
    #[serde(rename = "pv_employee")]
    pub pv_employee: String,
    #[serde(rename = "pv_employer")]
    pub pv_employer: String,
    #[serde(rename = "run_id")]
    pub run_id: uuid::Uuid,
    #[serde(rename = "rv_employee")]
    pub rv_employee: String,
    #[serde(rename = "rv_employer")]
    pub rv_employer: String,
    #[serde(rename = "sick_days")]
    pub sick_days: i32,
    #[serde(rename = "soli")]
    pub soli: String,
    #[serde(rename = "status")]
    pub status: models::PayrollRunStatus,
    #[serde(rename = "total_deductions")]
    pub total_deductions: String,
    #[serde(rename = "total_employer_cost")]
    pub total_employer_cost: String,
    #[serde(rename = "vacation_days_used")]
    pub vacation_days_used: i32,
}

impl PayrollEntryApi {
    pub fn new(av_employee: String, av_employer: String, church_tax_amount: String, employee_id: uuid::Uuid, entry_id: uuid::Uuid, extra_payments: String, gross_salary: String, kv_employee: String, kv_employer: String, lohnsteuer: String, net_salary: String, pv_employee: String, pv_employer: String, run_id: uuid::Uuid, rv_employee: String, rv_employer: String, sick_days: i32, soli: String, status: models::PayrollRunStatus, total_deductions: String, total_employer_cost: String, vacation_days_used: i32) -> PayrollEntryApi {
        PayrollEntryApi {
            av_employee,
            av_employer,
            church_tax_amount,
            employee: None,
            employee_id,
            entry_id,
            extra_payment_reason: None,
            extra_payments,
            gross_salary,
            kv_employee,
            kv_employer,
            lohnsteuer,
            net_salary,
            notes: None,
            pv_employee,
            pv_employer,
            run_id,
            rv_employee,
            rv_employer,
            sick_days,
            soli,
            status,
            total_deductions,
            total_employer_cost,
            vacation_days_used,
        }
    }
}

