/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PayrollCreatePayload {
    #[serde(rename = "employee_ids")]
    pub employee_ids: Vec<uuid::Uuid>,
    #[serde(rename = "extra_payments", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub extra_payments: Option<Option<Vec<models::ExtraPayment>>>,
    #[serde(rename = "month")]
    pub month: i32,
    #[serde(rename = "year")]
    pub year: i32,
}

impl PayrollCreatePayload {
    pub fn new(employee_ids: Vec<uuid::Uuid>, month: i32, year: i32) -> PayrollCreatePayload {
        PayrollCreatePayload {
            employee_ids,
            extra_payments: None,
            month,
            year,
        }
    }
}

