/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlatformInfo : Public metadata for one registered plugin (admin UI). Maps 1:1 from [`plugin_core::PluginInfo`] (same field shape as before).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformInfo {
    #[serde(rename = "author")]
    pub author: String,
    #[serde(rename = "changelog")]
    pub changelog: Vec<models::ChangelogEntry>,
    #[serde(rename = "config_field_names")]
    pub config_field_names: Vec<String>,
    #[serde(rename = "config_fields")]
    pub config_fields: Vec<models::ConfigFieldInfo>,
    #[serde(rename = "display_name")]
    pub display_name: String,
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "pricing")]
    pub pricing: Box<models::PluginPricing>,
    #[serde(rename = "supported_entities")]
    pub supported_entities: Vec<String>,
    #[serde(rename = "supports_export")]
    pub supports_export: bool,
    #[serde(rename = "supports_import")]
    pub supports_import: bool,
    #[serde(rename = "supports_oauth")]
    pub supports_oauth: bool,
    #[serde(rename = "version")]
    pub version: String,
}

impl PlatformInfo {
    /// Public metadata for one registered plugin (admin UI). Maps 1:1 from [`plugin_core::PluginInfo`] (same field shape as before).
    pub fn new(author: String, changelog: Vec<models::ChangelogEntry>, config_field_names: Vec<String>, config_fields: Vec<models::ConfigFieldInfo>, display_name: String, platform: String, pricing: models::PluginPricing, supported_entities: Vec<String>, supports_export: bool, supports_import: bool, supports_oauth: bool, version: String) -> PlatformInfo {
        PlatformInfo {
            author,
            changelog,
            config_field_names,
            config_fields,
            display_name,
            platform,
            pricing: Box::new(pricing),
            supported_entities,
            supports_export,
            supports_import,
            supports_oauth,
            version,
        }
    }
}

