/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PluginError {
    PluginErrorOneOf(Box<models::PluginErrorOneOf>),
    PluginErrorOneOf1(Box<models::PluginErrorOneOf1>),
    PluginErrorOneOf2(Box<models::PluginErrorOneOf2>),
    PluginErrorOneOf3(Box<models::PluginErrorOneOf3>),
    PluginErrorOneOf4(Box<models::PluginErrorOneOf4>),
    PluginErrorOneOf5(Box<models::PluginErrorOneOf5>),
    PluginErrorOneOf6(Box<models::PluginErrorOneOf6>),
}

impl Default for PluginError {
    fn default() -> Self {
        Self::PluginErrorOneOf(Default::default())
    }
}

