/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductVariantUpdate {
    #[serde(rename = "barcode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub barcode: Option<Option<String>>,
    #[serde(rename = "imageLink", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub image_link: Option<Option<String>>,
    #[serde(rename = "isActive", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<Option<bool>>,
    /// Human-readable variant label, e.g. \"Red / M\".
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    /// Option name → value map, e.g. `{\"Color\": \"Red\", \"Size\": \"M\"}`.
    #[serde(rename = "optionValues", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub option_values: Option<Option<serde_json::Value>>,
    /// Explicit override price for this variant (takes precedence over parent price + delta).
    #[serde(rename = "price", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub price: Option<Option<String>>,
    /// Price adjustment relative to the parent product's `default_price`.
    #[serde(rename = "priceDelta", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub price_delta: Option<Option<String>>,
    /// The parent product this variant belongs to. References the product entity.
    #[serde(rename = "productId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub product_id: Option<Option<uuid::Uuid>>,
    /// Variant-specific SKU (must be unique per tenant).
    #[serde(rename = "sku", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sku: Option<Option<String>>,
    /// Variant-level stock (optional — may be tracked on the parent only).
    #[serde(rename = "stockQuantity", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub stock_quantity: Option<Option<i64>>,
}

impl ProductVariantUpdate {
    pub fn new() -> ProductVariantUpdate {
        ProductVariantUpdate {
            barcode: None,
            image_link: None,
            is_active: None,
            name: None,
            option_values: None,
            price: None,
            price_delta: None,
            product_id: None,
            sku: None,
            stock_quantity: None,
        }
    }
}

