/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductUpdate {
    #[serde(rename = "availability", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub availability: Option<Option<String>>,
    #[serde(rename = "barcode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub barcode: Option<Option<String>>,
    #[serde(rename = "brand", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub brand: Option<Option<String>>,
    #[serde(rename = "categoryId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub category_id: Option<Option<String>>,
    #[serde(rename = "condition", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub condition: Option<Option<String>>,
    #[serde(rename = "defaultLedgerAccount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub default_ledger_account: Option<Option<String>>,
    #[serde(rename = "defaultPrice", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub default_price: Option<Option<String>>,
    /// References the price formula entity.
    #[serde(rename = "defaultPriceFormulaId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub default_price_formula_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "defaultTaxRate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub default_tax_rate: Option<Option<String>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "gtin", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gtin: Option<Option<String>>,
    #[serde(rename = "height", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub height: Option<Option<String>>,
    #[serde(rename = "imageLink", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub image_link: Option<Option<String>>,
    #[serde(rename = "images", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub images: Option<Option<serde_json::Value>>,
    #[serde(rename = "isTaxable", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_taxable: Option<Option<bool>>,
    #[serde(rename = "length", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub length: Option<Option<String>>,
    #[serde(rename = "link", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub link: Option<Option<String>>,
    /// Target stock level used by reorder proposals.
    #[serde(rename = "maxStock", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_stock: Option<Option<i64>>,
    /// Reorder point — when stock falls below this, a reorder is suggested.
    #[serde(rename = "minStock", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub min_stock: Option<Option<i64>>,
    #[serde(rename = "mpn", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mpn: Option<Option<String>>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "packageHeight", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub package_height: Option<Option<String>>,
    #[serde(rename = "packageLength", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub package_length: Option<Option<String>>,
    #[serde(rename = "packageWeightUnit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub package_weight_unit: Option<Option<String>>,
    #[serde(rename = "packageWeightValue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub package_weight_value: Option<Option<String>>,
    #[serde(rename = "packageWidth", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub package_width: Option<Option<String>>,
    #[serde(rename = "productCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub product_code: Option<Option<String>>,
    #[serde(rename = "productType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub product_type: Option<Option<String>>,
    #[serde(rename = "purchasePrice", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub purchase_price: Option<Option<String>>,
    /// Suggested purchase quantity when a reorder proposal is created.
    #[serde(rename = "reorderQuantity", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reorder_quantity: Option<Option<i64>>,
    #[serde(rename = "salePrice", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sale_price: Option<Option<String>>,
    #[serde(rename = "shippingPrice", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub shipping_price: Option<Option<String>>,
    #[serde(rename = "shippingRequiresInsurance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub shipping_requires_insurance: Option<Option<bool>>,
    #[serde(rename = "sku", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sku: Option<Option<String>>,
    #[serde(rename = "stockQuantity", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub stock_quantity: Option<Option<i64>>,
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<serde_json::Value>>,
    #[serde(rename = "taxPrice", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tax_price: Option<Option<String>>,
    /// Whether this product requires batch (Chargennummer) tracking.
    #[serde(rename = "trackBatch", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub track_batch: Option<Option<bool>>,
    /// Whether this product requires serial-number tracking.
    #[serde(rename = "trackSerial", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub track_serial: Option<Option<bool>>,
    #[serde(rename = "unit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unit: Option<Option<serde_json::Value>>,
    #[serde(rename = "weightUnit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub weight_unit: Option<Option<String>>,
    #[serde(rename = "weightValue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub weight_value: Option<Option<String>>,
    #[serde(rename = "width", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub width: Option<Option<String>>,
}

impl ProductUpdate {
    pub fn new() -> ProductUpdate {
        ProductUpdate {
            availability: None,
            barcode: None,
            brand: None,
            category_id: None,
            condition: None,
            default_ledger_account: None,
            default_price: None,
            default_price_formula_id: None,
            default_tax_rate: None,
            description: None,
            gtin: None,
            height: None,
            image_link: None,
            images: None,
            is_taxable: None,
            length: None,
            link: None,
            max_stock: None,
            min_stock: None,
            mpn: None,
            name: None,
            package_height: None,
            package_length: None,
            package_weight_unit: None,
            package_weight_value: None,
            package_width: None,
            product_code: None,
            product_type: None,
            purchase_price: None,
            reorder_quantity: None,
            sale_price: None,
            shipping_price: None,
            shipping_requires_insurance: None,
            sku: None,
            stock_quantity: None,
            tags: None,
            tax_price: None,
            track_batch: None,
            track_serial: None,
            unit: None,
            weight_unit: None,
            weight_value: None,
            width: None,
        }
    }
}

