/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductAttributeCreate {
    /// Whether this attribute participates in the shop's faceted filters.
    #[serde(rename = "isFilterable", skip_serializing_if = "Option::is_none")]
    pub is_filterable: Option<bool>,
    /// Attribute name, e.g. `Material`, `Farbe`, `Gewicht`.
    #[serde(rename = "name")]
    pub name: String,
    /// Ordering position within the product's attribute list.
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<i32>,
    /// The product this attribute belongs to. References the product entity.
    #[serde(rename = "productId")]
    pub product_id: uuid::Uuid,
    /// Optional unit of measure for numeric attributes, e.g. `g`, `cm`.
    #[serde(rename = "unit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unit: Option<Option<String>>,
    /// Attribute value, e.g. `Baumwolle`, `Rot`, `180g`.
    #[serde(rename = "value")]
    pub value: String,
}

impl ProductAttributeCreate {
    pub fn new(name: String, product_id: uuid::Uuid, value: String) -> ProductAttributeCreate {
        ProductAttributeCreate {
            is_filterable: None,
            name,
            position: None,
            product_id,
            unit: None,
            value,
        }
    }
}

