/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderInfo {
    #[serde(rename = "display_name")]
    pub display_name: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "requires_api_key")]
    pub requires_api_key: bool,
    #[serde(rename = "services")]
    pub services: Vec<String>,
    #[serde(rename = "supports_label_creation")]
    pub supports_label_creation: bool,
    #[serde(rename = "supports_rate_estimation")]
    pub supports_rate_estimation: bool,
    #[serde(rename = "supports_tracking")]
    pub supports_tracking: bool,
}

impl ProviderInfo {
    pub fn new(display_name: String, name: String, requires_api_key: bool, services: Vec<String>, supports_label_creation: bool, supports_rate_estimation: bool, supports_tracking: bool) -> ProviderInfo {
        ProviderInfo {
            display_name,
            name,
            requires_api_key,
            services,
            supports_label_creation,
            supports_rate_estimation,
            supports_tracking,
        }
    }
}

