/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuartileBand {
    #[serde(rename = "female_share_pct")]
    pub female_share_pct: f64,
    #[serde(rename = "hourly_median")]
    pub hourly_median: String,
    #[serde(rename = "male_share_pct")]
    pub male_share_pct: f64,
    #[serde(rename = "quartile")]
    pub quartile: String,
}

impl QuartileBand {
    pub fn new(female_share_pct: f64, hourly_median: String, male_share_pct: f64, quartile: String) -> QuartileBand {
        QuartileBand {
            female_share_pct,
            hourly_median,
            male_share_pct,
            quartile,
        }
    }
}

