/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuizQuestion {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "options")]
    pub options: Vec<String>,
    #[serde(rename = "optionsEn")]
    pub options_en: Vec<String>,
    #[serde(rename = "question")]
    pub question: String,
    #[serde(rename = "questionEn")]
    pub question_en: String,
}

impl QuizQuestion {
    pub fn new(id: String, options: Vec<String>, options_en: Vec<String>, question: String, question_en: String) -> QuizQuestion {
        QuizQuestion {
            id,
            options,
            options_en,
            question,
            question_en,
        }
    }
}

