/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RateRequest {
    #[serde(rename = "customer", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub customer: Option<Option<Box<models::CustomerInfo>>>,
    #[serde(rename = "packages")]
    pub packages: Vec<models::Package>,
    #[serde(rename = "recipient")]
    pub recipient: Box<models::Address>,
    #[serde(rename = "sender")]
    pub sender: Box<models::Address>,
}

impl RateRequest {
    pub fn new(packages: Vec<models::Package>, recipient: models::Address, sender: models::Address) -> RateRequest {
        RateRequest {
            customer: None,
            packages,
            recipient: Box::new(recipient),
            sender: Box::new(sender),
        }
    }
}

