/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReferenceType : Stock movement reference type.
/// Stock movement reference type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReferenceType {
    #[serde(rename = "goods_receipt")]
    GoodsReceipt,
    #[serde(rename = "production_order")]
    ProductionOrder,
    #[serde(rename = "transfer_in")]
    TransferIn,
    #[serde(rename = "stock_transfer")]
    StockTransfer,
    #[serde(rename = "return_order")]
    ReturnOrder,
    #[serde(rename = "inventory_count")]
    InventoryCount,

}

impl std::fmt::Display for ReferenceType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::GoodsReceipt => write!(f, "goods_receipt"),
            Self::ProductionOrder => write!(f, "production_order"),
            Self::TransferIn => write!(f, "transfer_in"),
            Self::StockTransfer => write!(f, "stock_transfer"),
            Self::ReturnOrder => write!(f, "return_order"),
            Self::InventoryCount => write!(f, "inventory_count"),
        }
    }
}

impl Default for ReferenceType {
    fn default() -> ReferenceType {
        Self::GoodsReceipt
    }
}

