/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReturnLogisticsSummary : Warehouse-level aggregation for the returns logistics dashboard.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReturnLogisticsSummary {
    /// Number of return orders per status.
    #[serde(rename = "byStatus", deserialize_with = "Option::deserialize")]
    pub by_status: Option<serde_json::Value>,
    /// Per-warehouse aggregation.
    #[serde(rename = "byWarehouse")]
    pub by_warehouse: Vec<models::ReturnWarehouseSummary>,
    /// Sum of `restock: true` line-item quantities.
    #[serde(rename = "itemsRestocked")]
    pub items_restocked: i64,
    /// Sum of `restock: false` line-item quantities (scrapped/disposed).
    #[serde(rename = "itemsScrapped")]
    pub items_scrapped: i64,
    /// Sum of all line-item quantities across returns.
    #[serde(rename = "totalItems")]
    pub total_items: i64,
    /// Total number of return orders (excluding soft-deleted).
    #[serde(rename = "totalReturns")]
    pub total_returns: i64,
}

impl ReturnLogisticsSummary {
    /// Warehouse-level aggregation for the returns logistics dashboard.
    pub fn new(by_status: Option<serde_json::Value>, by_warehouse: Vec<models::ReturnWarehouseSummary>, items_restocked: i64, items_scrapped: i64, total_items: i64, total_returns: i64) -> ReturnLogisticsSummary {
        ReturnLogisticsSummary {
            by_status,
            by_warehouse,
            items_restocked,
            items_scrapped,
            total_items,
            total_returns,
        }
    }
}

