/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReturnWarehouseSummary : Aggregation for a single warehouse.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReturnWarehouseSummary {
    #[serde(rename = "itemsRestocked")]
    pub items_restocked: i64,
    #[serde(rename = "itemsScrapped")]
    pub items_scrapped: i64,
    #[serde(rename = "returns")]
    pub returns: i64,
    #[serde(rename = "warehouseId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub warehouse_id: Option<Option<String>>,
}

impl ReturnWarehouseSummary {
    /// Aggregation for a single warehouse.
    pub fn new(items_restocked: i64, items_scrapped: i64, returns: i64) -> ReturnWarehouseSummary {
        ReturnWarehouseSummary {
            items_restocked,
            items_scrapped,
            returns,
            warehouse_id: None,
        }
    }
}

