/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceJobCreate {
    /// Street + zip + city of the job location.
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// Customer email for email notifications.
    #[serde(rename = "customerEmail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub customer_email: Option<Option<String>>,
    /// References the customer entity.
    #[serde(rename = "customerId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub customer_id: Option<Option<uuid::Uuid>>,
    /// Denormalized customer name for quick display.
    #[serde(rename = "customerName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub customer_name: Option<Option<String>>,
    /// Customer phone for SMS notifications later.
    #[serde(rename = "customerPhone", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub customer_phone: Option<Option<String>>,
    /// What work needs to be done.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Estimated time for the job in minutes.
    #[serde(rename = "estimatedDurationMinutes", skip_serializing_if = "Option::is_none")]
    pub estimated_duration_minutes: Option<i32>,
    /// Latitude for map display (OpenStreetMap).
    #[serde(rename = "lat", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub lat: Option<Option<f64>>,
    /// Longitude for map display (OpenStreetMap).
    #[serde(rename = "lng", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub lng: Option<Option<f64>>,
    #[serde(rename = "notes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Option<String>>,
    /// Dispatch status: \"pending\", \"assigned\", \"en_route\", \"in_progress\", \"completed\", \"cancelled\".
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::ServiceJobStatus>,
}

impl ServiceJobCreate {
    pub fn new() -> ServiceJobCreate {
        ServiceJobCreate {
            address: None,
            customer_email: None,
            customer_id: None,
            customer_name: None,
            customer_phone: None,
            description: None,
            estimated_duration_minutes: None,
            lat: None,
            lng: None,
            notes: None,
            status: None,
        }
    }
}

