/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceAssignmentCreate {
    /// References the employees entity.
    #[serde(rename = "employeeId", skip_serializing_if = "Option::is_none")]
    pub employee_id: Option<uuid::Uuid>,
    /// References the service_jobs entity.
    #[serde(rename = "jobId", skip_serializing_if = "Option::is_none")]
    pub job_id: Option<uuid::Uuid>,
    #[serde(rename = "notes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Option<String>>,
    /// Work day the assignment is scheduled for.
    #[serde(rename = "scheduledDate", skip_serializing_if = "Option::is_none")]
    pub scheduled_date: Option<chrono::NaiveDate>,
    /// Planned end time of the assignment.
    #[serde(rename = "scheduledEnd", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scheduled_end: Option<Option<String>>,
    /// Planned start time of the assignment.
    #[serde(rename = "scheduledStart", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scheduled_start: Option<Option<String>>,
    /// Assignment lifecycle status: \"planned\", \"confirmed\", \"en_route\", \"in_progress\", \"completed\" or \"cancelled\".
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::ServiceAssignmentStatus>,
}

impl ServiceAssignmentCreate {
    pub fn new() -> ServiceAssignmentCreate {
        ServiceAssignmentCreate {
            employee_id: None,
            job_id: None,
            notes: None,
            scheduled_date: None,
            scheduled_end: None,
            scheduled_start: None,
            status: None,
        }
    }
}

