/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ShippingCredentials : Per-tenant credentials for real shipping provider APIs (stored in the `shipping` key of the settings JSON blob). Auth is either OAuth client credentials (UPS) or a user-supplied API key (DHL).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShippingCredentials {
    #[serde(rename = "dhl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub dhl: Option<Option<Box<models::DhlCredentials>>>,
    #[serde(rename = "ups", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ups: Option<Option<Box<models::UpsCredentials>>>,
}

impl ShippingCredentials {
    /// Per-tenant credentials for real shipping provider APIs (stored in the `shipping` key of the settings JSON blob). Auth is either OAuth client credentials (UPS) or a user-supplied API key (DHL).
    pub fn new() -> ShippingCredentials {
        ShippingCredentials {
            dhl: None,
            ups: None,
        }
    }
}

