/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SilentPartner {
    /// Datum des Vertragsabschlusses.
    #[serde(rename = "contractDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub contract_date: Option<Option<chrono::NaiveDate>>,
    /// Einlage (§ 230 HGB).
    #[serde(rename = "einlage", skip_serializing_if = "Option::is_none")]
    pub einlage: Option<String>,
    /// Gewinnbeteiligungsquote in Prozent (§ 231 HGB).
    #[serde(rename = "gewinnquotePct", skip_serializing_if = "Option::is_none")]
    pub gewinnquote_pct: Option<String>,
    /// Nicht erhobene Gewinne (§ 232 Abs. 3 HGB).
    #[serde(rename = "gewinnvortrag", skip_serializing_if = "Option::is_none")]
    pub gewinnvortrag: Option<String>,
    /// Instrument: \"typisch\" | \"atypisch\" | \"partiarisches_darlehen\" | \"genussrecht\".
    #[serde(rename = "instrumentType")]
    pub instrument_type: models::InstrumentType,
    /// 25 % Kapitalertragsteuer einbehalten (§ 43 Abs. 1 Nr. 3 EStG; typisch + partiarisches Darlehen).
    #[serde(rename = "kestPflichtig", skip_serializing_if = "Option::is_none")]
    pub kest_pflichtig: Option<bool>,
    /// Name des stillen Gesellschafters.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Freitext-Notizen.
    #[serde(rename = "notes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Option<String>>,
    /// Kumulierte Verluste gegen die Einlage (§ 232 Abs. 2 HGB, ≤ Einlage).
    #[serde(rename = "verlustVerrechnungskonto", skip_serializing_if = "Option::is_none")]
    pub verlust_verrechnungskonto: Option<String>,
    /// Verlustbeteiligung (§ 231 Abs. 2 HGB; kann ausgeschlossen werden).
    #[serde(rename = "verlustbeteiligung", skip_serializing_if = "Option::is_none")]
    pub verlustbeteiligung: Option<bool>,
}

impl SilentPartner {
    pub fn new(instrument_type: models::InstrumentType) -> SilentPartner {
        SilentPartner {
            contract_date: None,
            einlage: None,
            gewinnquote_pct: None,
            gewinnvortrag: None,
            instrument_type,
            kest_pflichtig: None,
            name: None,
            notes: None,
            verlust_verrechnungskonto: None,
            verlustbeteiligung: None,
        }
    }
}

