/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StillePartnerZeile {
    #[serde(rename = "auseinandersetzungsguthaben")]
    pub auseinandersetzungsguthaben: String,
    #[serde(rename = "gewinnanteil")]
    pub gewinnanteil: String,
    #[serde(rename = "gewinnvortrag")]
    pub gewinnvortrag: String,
    #[serde(rename = "hinweis", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub hinweis: Option<Option<String>>,
    #[serde(rename = "instrument_type")]
    pub instrument_type: String,
    #[serde(rename = "kest")]
    pub kest: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "verlust_verrechnungskonto")]
    pub verlust_verrechnungskonto: String,
    #[serde(rename = "verlustanteil")]
    pub verlustanteil: String,
}

impl StillePartnerZeile {
    pub fn new(auseinandersetzungsguthaben: String, gewinnanteil: String, gewinnvortrag: String, instrument_type: String, kest: String, name: String, verlust_verrechnungskonto: String, verlustanteil: String) -> StillePartnerZeile {
        StillePartnerZeile {
            auseinandersetzungsguthaben,
            gewinnanteil,
            gewinnvortrag,
            hinweis: None,
            instrument_type,
            kest,
            name,
            verlust_verrechnungskonto,
            verlustanteil,
        }
    }
}

