/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SuitabilityRequest {
    #[serde(rename = "customer_annual_volume", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub customer_annual_volume: Option<Option<i32>>,
    #[serde(rename = "items")]
    pub items: Vec<models::CartItemInput>,
    #[serde(rename = "recipient")]
    pub recipient: Box<models::Address>,
    #[serde(rename = "sender")]
    pub sender: Box<models::Address>,
}

impl SuitabilityRequest {
    pub fn new(items: Vec<models::CartItemInput>, recipient: models::Address, sender: models::Address) -> SuitabilityRequest {
        SuitabilityRequest {
            customer_annual_volume: None,
            items,
            recipient: Box::new(recipient),
            sender: Box::new(sender),
        }
    }
}

