/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SupplierInvoiceUpdate {
    #[serde(rename = "currency", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub currency: Option<Option<String>>,
    /// References the goods receipt entity.
    #[serde(rename = "goodsReceiptId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub goods_receipt_id: Option<Option<String>>,
    #[serde(rename = "invoiceDate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub invoice_date: Option<Option<chrono::NaiveDate>>,
    #[serde(rename = "invoiceNumber", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub invoice_number: Option<Option<String>>,
    /// JSON array of `{product_id, name, quantity, unitPriceNet, taxRate}`.
    #[serde(rename = "lineItems", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub line_items: Option<Option<serde_json::Value>>,
    #[serde(rename = "notes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Option<String>>,
    /// References the purchase order entity.
    #[serde(rename = "purchaseOrderId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub purchase_order_id: Option<Option<String>>,
    /// One of: draft | matched | has_variances | posted | cancelled
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<models::SupplierInvoiceStatus>>,
    /// References the supplier entity.
    #[serde(rename = "supplierContactId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub supplier_contact_id: Option<Option<String>>,
    #[serde(rename = "supplierName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub supplier_name: Option<Option<String>>,
    #[serde(rename = "totalGrossAmount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_gross_amount: Option<Option<String>>,
    #[serde(rename = "totalNetAmount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_net_amount: Option<Option<String>>,
}

impl SupplierInvoiceUpdate {
    pub fn new() -> SupplierInvoiceUpdate {
        SupplierInvoiceUpdate {
            currency: None,
            goods_receipt_id: None,
            invoice_date: None,
            invoice_number: None,
            line_items: None,
            notes: None,
            purchase_order_id: None,
            status: None,
            supplier_contact_id: None,
            supplier_name: None,
            total_gross_amount: None,
            total_net_amount: None,
        }
    }
}

