/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncLog {
    #[serde(rename = "completed_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "connection_id")]
    pub connection_id: String,
    #[serde(rename = "error_message", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<Option<String>>,
    #[serde(rename = "items_failed")]
    pub items_failed: i32,
    #[serde(rename = "items_synced")]
    pub items_synced: i32,
    #[serde(rename = "log_id")]
    pub log_id: String,
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "started_at")]
    pub started_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "sync_type")]
    pub sync_type: String,
}

impl SyncLog {
    pub fn new(connection_id: String, items_failed: i32, items_synced: i32, log_id: String, platform: String, started_at: chrono::DateTime<chrono::FixedOffset>, status: String, sync_type: String) -> SyncLog {
        SyncLog {
            completed_at: None,
            connection_id,
            error_message: None,
            items_failed,
            items_synced,
            log_id,
            platform,
            started_at,
            status,
            sync_type,
        }
    }
}

