/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TicketMessage {
    #[serde(rename = "authorEmail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub author_email: Option<Option<String>>,
    #[serde(rename = "authorName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub author_name: Option<Option<String>>,
    #[serde(rename = "body")]
    pub body: String,
    #[serde(rename = "bodyHtml", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub body_html: Option<Option<String>>,
    #[serde(rename = "channelId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "direction")]
    pub direction: models::MessageDirection,
    #[serde(rename = "externalId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub external_id: Option<Option<String>>,
    #[serde(rename = "isInternal")]
    pub is_internal: bool,
    #[serde(rename = "messageType")]
    pub message_type: models::MessageType,
    #[serde(rename = "metadata", deserialize_with = "Option::deserialize")]
    pub metadata: Option<serde_json::Value>,
    #[serde(rename = "tenantId")]
    pub tenant_id: uuid::Uuid,
    /// References the ticket entity.
    #[serde(rename = "ticketId")]
    pub ticket_id: uuid::Uuid,
}

impl TicketMessage {
    pub fn new(body: String, created_at: chrono::DateTime<chrono::FixedOffset>, direction: models::MessageDirection, is_internal: bool, message_type: models::MessageType, metadata: Option<serde_json::Value>, tenant_id: uuid::Uuid, ticket_id: uuid::Uuid) -> TicketMessage {
        TicketMessage {
            author_email: None,
            author_name: None,
            body,
            body_html: None,
            channel_id: None,
            created_at,
            direction,
            external_id: None,
            is_internal,
            message_type,
            metadata,
            tenant_id,
            ticket_id,
        }
    }
}

