/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UmsatzsteuerReport {
    #[serde(rename = "generated_at")]
    pub generated_at: String,
    #[serde(rename = "input_tax")]
    pub input_tax: Vec<models::VatDetail>,
    #[serde(rename = "output_tax")]
    pub output_tax: Vec<models::VatDetail>,
    #[serde(rename = "period")]
    pub period: String,
    #[serde(rename = "total_input_tax")]
    pub total_input_tax: String,
    #[serde(rename = "total_output_tax")]
    pub total_output_tax: String,
    #[serde(rename = "vat_payable")]
    pub vat_payable: String,
    #[serde(rename = "vat_refund")]
    pub vat_refund: String,
}

impl UmsatzsteuerReport {
    pub fn new(generated_at: String, input_tax: Vec<models::VatDetail>, output_tax: Vec<models::VatDetail>, period: String, total_input_tax: String, total_output_tax: String, vat_payable: String, vat_refund: String) -> UmsatzsteuerReport {
        UmsatzsteuerReport {
            generated_at,
            input_tax,
            output_tax,
            period,
            total_input_tax,
            total_output_tax,
            vat_payable,
            vat_refund,
        }
    }
}

