/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateConnectionRequest {
    #[serde(rename = "api_key", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<Option<String>>,
    #[serde(rename = "api_secret", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub api_secret: Option<Option<String>>,
    #[serde(rename = "config", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub config: Option<Option<serde_json::Value>>,
    #[serde(rename = "is_active", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<Option<bool>>,
    #[serde(rename = "label", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub label: Option<Option<String>>,
    #[serde(rename = "shop_domain", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub shop_domain: Option<Option<String>>,
}

impl UpdateConnectionRequest {
    pub fn new() -> UpdateConnectionRequest {
        UpdateConnectionRequest {
            api_key: None,
            api_secret: None,
            config: None,
            is_active: None,
            label: None,
            shop_domain: None,
        }
    }
}

