/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateTenantSettings : Request payload for updating tenant settings.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTenantSettings {
    #[serde(rename = "companyType")]
    pub company_type: models::CompanyType,
    #[serde(rename = "features", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub features: Option<Option<Box<models::PartialFeatureSettings>>>,
}

impl UpdateTenantSettings {
    /// Request payload for updating tenant settings.
    pub fn new(company_type: models::CompanyType) -> UpdateTenantSettings {
        UpdateTenantSettings {
            company_type,
            features: None,
        }
    }
}

