/*
 * SimpleBilly API
 *
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct YearlyPayrollSummary {
    #[serde(rename = "avg_employee_count")]
    pub avg_employee_count: i32,
    #[serde(rename = "months")]
    pub months: Vec<models::PayrollSummaryItem>,
    #[serde(rename = "year")]
    pub year: i32,
    #[serde(rename = "yearly_employer_cost")]
    pub yearly_employer_cost: String,
    #[serde(rename = "yearly_gross")]
    pub yearly_gross: String,
    #[serde(rename = "yearly_net")]
    pub yearly_net: String,
}

impl YearlyPayrollSummary {
    pub fn new(avg_employee_count: i32, months: Vec<models::PayrollSummaryItem>, year: i32, yearly_employer_cost: String, yearly_gross: String, yearly_net: String) -> YearlyPayrollSummary {
        YearlyPayrollSummary {
            avg_employee_count,
            months,
            year,
            yearly_employer_cost,
            yearly_gross,
            yearly_net,
        }
    }
}

